In [5]:
from LapMCCA import LapMCCA
import numpy as np
lapmcca=LapMCCA(3,2)

In [8]:
a = np.array([[-1, -4, 3,3], [-25, -1,4,40], [-33, -24,23,34], [1, 1,45,23], [23, 1,1,34], [3, 24,34,25]])
b = np.array([[-1, -1,2,3], [-2,2, -1,-3], [-3,4, -2,0], [1,2, 1,8], [2,3, 1,5], [3, 4,2,3],[0,1, 0,7]])
c = np.array([[-1, -1,3,2], [-2, 3,-1,5], [-3, 4,-2,7], [1, 1,3,1], [2, 1,3,4], [3,4, 2,6],[0,2, 0,0],[2,4,7,90]])
X=np.array([a,b,c])
label=np.array([[1,1,2,2],
                [0,0,1,1],
                [0,1,1,0]])
alpha=lapmcca.fit(X,label)
print(np.array(alpha))


[array([[ 0.00244387,  0.00139901,  0.00139577],
       [-0.66832646, -0.66044211, -0.66041733],
       [-0.20555693, -0.20257898, -0.20256961],
       [ 0.39657576,  0.39676392,  0.39676461],
       [-0.57683945, -0.5848865 , -0.58491128],
       [ 0.14513455,  0.15251947,  0.15254241]])
 array([[ 0.07470596, -0.09038759, -0.08953872],
       [ 0.03201904,  0.19290451,  0.17393524],
       [ 0.46558397, -0.15954896, -0.1880763 ],
       [ 0.56767115, -0.62968083, -0.6280566 ],
       [ 0.34364169, -0.35851806, -0.35944044],
       [ 0.1197497 , -0.08735528, -0.09082427],
       [ 0.56740218, -0.62968085, -0.6280566 ]])
 array([[ 3.17513534e-02,  3.48551145e-02,  3.48940223e-02],
       [ 8.07776166e-02,  7.74787474e-02,  7.74374831e-02],
       [ 1.15541424e-01,  1.10601428e-01,  1.10539649e-01],
       [-1.00436832e-03,  5.77477961e-04,  5.97285348e-04],
       [ 2.14998848e-02,  2.30442503e-02,  2.30635864e-02],
       [ 3.47674328e-02,  3.31226806e-02,  3.31021663e-02],
       [ 1.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  after removing the cwd from sys.path.
/content/LapMCCA.py:98: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  S_w_view=np.array(S_w_view)
/content/LapMCCA.py:114: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Wij=np.array(Wij)
/c

In [9]:
Xnew=lapmcca.fit_transform(X,label)
print(np.array(Xnew))

[[[-19.79821442  -6.63298693  -7.10221061  45.59369457]
  [-14.50579821  -8.11305169 -11.99688055  42.88333295]
  [-12.18591915  -8.65283495 -13.91456354  41.37779424]]

 [[  1.00921197   4.05582452   0.95015999  12.02797525]
  [  1.22419835   3.76727272   1.08876333  12.21647643]
  [  1.27700746   3.69291673   1.12263617  12.25560845]]

 [[  1.58598885   4.78473105   6.83905367  90.55161172]
  [  1.60325422   4.75250744   6.8688732   90.56920862]
  [  1.60346973   4.75210402   6.86924509  90.56940382]]]


/content/LapMCCA.py:98: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  S_w_view=np.array(S_w_view)
/content/LapMCCA.py:114: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Wij=np.array(Wij)
/content/LapMCCA.py:125: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Dij=np.array(Dij)
/content/LapMCCA.py:136: VisibleDeprecationWarning: Creating 