# 2D SPCCA

In [10]:
from spcca2d import SPCCA2D
import pandas as pd
import numpy as np

In [11]:
x=pd.read_csv(r'mfeat-mor.csv',delim_whitespace=True,header=None)
y=pd.read_csv(r'mfeat-fou.csv',delim_whitespace=True,header=None)

In [12]:
print("Enter the K value where K is the number of nearest neighbors to consider:")
k=int(input())

Enter the K value where K is the number of nearest neighbors to consider:
3


In [13]:
spcca2D=SPCCA2D(x,y,k)
ProjectionVectorX,ProjectionVectorY=spcca2D.fit_transform()
print("Reduced Dimension Matrix X :")
print(ProjectionVectorX)
print("Reduced Dimension Matrix Y :")
print(ProjectionVectorY)

Reduced Dimension Matrix X :
[[-1.14612366e+03 -8.24000051e+01  1.10671844e+00 -1.20930114e+00
  -8.17003069e+01 -1.14707613e+03]
 [-1.13845041e+03 -7.79060554e+01  1.04279674e+00 -1.16849206e+00
  -7.72715911e+01 -1.13925783e+03]
 [-1.10989871e+03 -8.13654791e+01  1.08705215e+00 -1.19674696e+00
  -8.07049561e+01 -1.11080658e+03]
 ...
 [-2.66395736e+03 -6.74062145e+01 -2.42940975e-01 -9.09620135e-01
  -6.68230411e+01 -2.66476429e+03]
 [-2.91248742e+03 -7.07598853e+01 -1.60827681e-01 -9.62027661e-01
  -6.98877196e+01 -2.91351641e+03]
 [-2.69314297e+03 -6.65509900e+01 -2.50424121e-01 -9.04845592e-01
  -6.59996183e+01 -2.69391196e+03]]
Reduced Dimension Matrix Y :
[[-0.89755259 -0.3284455   0.18450625 ... -0.12449919  0.06522297
   0.49201895]
 [-0.85171999 -0.35682165  0.23604607 ... -0.11502197  0.09312587
   0.43923014]
 [-0.85428583 -0.34201337  0.21914897 ... -0.14107332  0.04925706
   0.41531466]
 ...
 [-0.95538801 -0.17889467  0.06654858 ... -0.21742447  0.01269367
   0.58114303]
 

# Example 1 using 4X3 and 4X2 Matrix

In [14]:
X = [[0.7, 0.5, 1.], [1.,0.1,0.9], [2.,2.,2.], [4.1,3.,3.]]
Y = [[0.2, -0.9], [0.7, 1.2], [7.2, 3.9], [12.9, 11.3]]
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [15]:
spcca2D=SPCCA2D(X,Y,3)
ProjectionVectorX,ProjectionVectorY=spcca2D.fit_transform()
print("Reduced Dimension Matrix X :")
print(ProjectionVectorX)
print("Reduced Dimension Matrix Y :")
print(ProjectionVectorY)

Reduced Dimension Matrix X :
[[ 1.11034833  0.08723552  0.70676484]
 [ 1.00304682  0.58530838  0.68652107]
 [ 3.30329169 -0.04910311  1.04204266]
 [ 5.68063708  0.73910397  1.4121217 ]]
Reduced Dimension Matrix Y :
[[  0.18483241  -0.90323695]
 [ -1.12889248   0.80969239]
 [ -8.16482743   0.62096141]
 [-16.38914638   5.04934462]]


# Example 2 using 4X3 and 4X2 Matrix

In [16]:
X = [[0.2, 0.3, 1.4], [1.1,0.3,0.4], [2.1,2.3,2.8], [3.2,1.2,3.5]]
Y = [[0.2, -0.1], [0.7, 1.3], [7.2, 4.9], [13.9, 11.3]]
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [17]:
spcca2D=SPCCA2D(X,Y,3)
ProjectionVectorX,ProjectionVectorY=spcca2D.fit_transform()
print("Reduced Dimension Matrix X :")
print(ProjectionVectorX)
print("Reduced Dimension Matrix Y :")
print(ProjectionVectorY)

Reduced Dimension Matrix X :
[[-1.21916941  0.26378173  0.73078393]
 [-0.1457697  -0.45276787  1.1107441 ]
 [-2.80274877 -1.47572837  2.73985859]
 [-2.46958317 -0.61927506  4.17703931]]
Reduced Dimension Matrix Y :
[[ -0.14274079  -0.17211934]
 [ -1.16453578   0.90766537]
 [ -8.5641325    1.58291959]
 [-17.27515772   4.74013983]]
