# Data Science Project




            
 


##  Project Topic: Multiview Linear Discriminant Analysis(MLDA) 

Prepared by 
1. Kanishk Gupta(0801CS171031) 
2. Harsh Pastaria (0801CS171027)
3. Aadeesh Jain(0801CS171001)
            

## Importing the required libraries

In [1]:


import numpy as np
import pandas as pd
import math

# Importing Datasets

In [2]:
X=pd.read_csv('mfeat-mor',delim_whitespace=True,header=None)

We are considering 2 datasets for multiview X,Y also these datasets uploaded in github for further info.

In [3]:
X

0    1    2           3         4            5
0     1.0  0.0  0.0  133.150861  1.311693  1620.221779
1     1.0  0.0  0.0  126.724861  1.302745  1609.334822
2     1.0  0.0  0.0  131.173861  1.319031  1568.978435
3     1.0  0.0  0.0  129.478861  1.270878  1695.055281
4     1.0  0.0  0.0  127.262861  1.329637  1647.720235
...   ...  ...  ...         ...       ...          ...
1995  1.0  1.0  1.0  157.498861  1.655794  5326.025889
1996  1.0  1.0  1.0  152.404861  1.620345  5243.267754
1997  1.0  1.0  1.0  134.672861  1.541987  3766.763222
1998  1.0  1.0  1.0  142.926861  1.426381  4118.327320
1999  1.0  1.0  1.0  133.920861  1.564621  3808.021317

[2000 rows x 6 columns]

Impritjg

In [4]:
Y=df=pd.read_csv('mfeat-pix',delim_whitespace=True,header=None)

In [5]:
Y

0    1    2    3    4    5    6    7    8    9    ...  230  231  232  \
0       0    3    4    4    6    6    6    6    6    5  ...    4    4    4   
1       0    0    0    0    0    0    1    3    4    4  ...    2    4    4   
2       0    0    1    4    4    4    4    4    4    3  ...    1    3    4   
3       0    0    3    3    2    2    4    5    6    6  ...    4    4    4   
4       0    0    0    0    0    0    3    4    6    6  ...    4    4    4   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1995    0    0    0    1    3    4    5    6    4    4  ...    4    4    4   
1996    0    0    0    0    3    6    6    6    6    6  ...    4    4    4   
1997    0    0    0    2    4    4    4    6    4    4  ...    0    2    4   
1998    0    0    0    0    0    0    2    4    4    5  ...    3    4    4   
1999    0    0    1    5    6    6    6    6    6    6  ...    4    4    1   

      233  234  235  236  237  238  239  
0       4    4    3    0    0    0    0  
1       4    4    2    0    0    0    0  
2       4    4    4    4    2    1    0  
3       4    2    0    0    0    0    0  
4       4    3    1    0    0    0    0  
...   ...  ...  ...  ...  ...  ...  ...  
1995    4    4    4    4    0    0    0  
1996    3    0    0    0    0    0    0  
1997    4    4    1    0    0    0    0  
1998    4    4    2    0    0    0    0  
1999    0    0    0    0    0    0    0  

[2000 rows x 240 columns]

Calculating shape of each dataset by using shape function

In [6]:
Y.shape

(2000, 240)

Reducing dataset column and rows for better results

In [7]:
Y=Y[:10]

In [8]:
Y

0    1    2    3    4    5    6    7    8    9    ...  230  231  232  233  \
0    0    3    4    4    6    6    6    6    6    5  ...    4    4    4    4   
1    0    0    0    0    0    0    1    3    4    4  ...    2    4    4    4   
2    0    0    1    4    4    4    4    4    4    3  ...    1    3    4    4   
3    0    0    3    3    2    2    4    5    6    6  ...    4    4    4    4   
4    0    0    0    0    0    0    3    4    6    6  ...    4    4    4    4   
5    0    0    0    0    0    0    0    0    0    5  ...    4    4    2    0   
6    0    3    4    4    6    6    6    5    4    5  ...    4    4    4    4   
7    0    0    0    3    6    6    6    6    6    6  ...    4    4    4    4   
8    0    0    3    4    6    6    6    6    6    6  ...    4    4    4    4   
9    0    1    2    4    4    4    4    4    4    4  ...    2    2    3    3   

   234  235  236  237  238  239  
0    4    3    0    0    0    0  
1    4    2    0    0    0    0  
2    4    4    4    2    1    0  
3    2    0    0    0    0    0  
4    3    1    0    0    0    0  
5    0    0    0    0    0    0  
6    4    4    4    3    0    0  
7    3    0    0    0    0    0  
8    4    4    4    4    1    0  
9    2    2    2    2    1    0  

[10 rows x 240 columns]

In [9]:
X=X[:10]
X

0    1    2           3         4            5
0  1.0  0.0  0.0  133.150861  1.311693  1620.221779
1  1.0  0.0  0.0  126.724861  1.302745  1609.334822
2  1.0  0.0  0.0  131.173861  1.319031  1568.978435
3  1.0  0.0  0.0  129.478861  1.270878  1695.055281
4  1.0  0.0  0.0  127.262861  1.329637  1647.720235
5  1.0  0.0  0.0  131.058861  1.310403  2027.211367
6  1.0  0.0  0.0  138.442861  1.379906  1918.750472
7  1.0  0.0  0.0  129.346861  1.305646  1547.263727
8  1.0  0.0  0.0  139.542861  1.374661  1871.055934
9  1.0  0.0  0.0  132.628861  1.374434  1884.680458

In [10]:
Y.drop(Y.iloc[:, 7:], inplace = True, axis = 1) 
  

c:\users\khushi\appdata\local\programs\python\python38-32\lib\site-packages\pandas\core\frame.py:4162: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [11]:
Y

0  1  2  3  4  5  6
0  0  3  4  4  6  6  6
1  0  0  0  0  0  0  1
2  0  0  1  4  4  4  4
3  0  0  3  3  2  2  4
4  0  0  0  0  0  0  3
5  0  0  0  0  0  0  0
6  0  3  4  4  6  6  6
7  0  0  0  3  6  6  6
8  0  0  3  4  6  6  6
9  0  1  2  4  4  4  4

Our both datsets have now equal no of rows and as well as columns for ex in this (6,6)

In [12]:
Y.drop(Y.iloc[:, 6:], inplace = True, axis = 1) 
  

c:\users\khushi\appdata\local\programs\python\python38-32\lib\site-packages\pandas\core\frame.py:4162: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [13]:
Y

0  1  2  3  4  5
0  0  3  4  4  6  6
1  0  0  0  0  0  0
2  0  0  1  4  4  4
3  0  0  3  3  2  2
4  0  0  0  0  0  0
5  0  0  0  0  0  0
6  0  3  4  4  6  6
7  0  0  0  3  6  6
8  0  0  3  4  6  6
9  0  1  2  4  4  4

In [14]:
X

0    1    2           3         4            5
0  1.0  0.0  0.0  133.150861  1.311693  1620.221779
1  1.0  0.0  0.0  126.724861  1.302745  1609.334822
2  1.0  0.0  0.0  131.173861  1.319031  1568.978435
3  1.0  0.0  0.0  129.478861  1.270878  1695.055281
4  1.0  0.0  0.0  127.262861  1.329637  1647.720235
5  1.0  0.0  0.0  131.058861  1.310403  2027.211367
6  1.0  0.0  0.0  138.442861  1.379906  1918.750472
7  1.0  0.0  0.0  129.346861  1.305646  1547.263727
8  1.0  0.0  0.0  139.542861  1.374661  1871.055934
9  1.0  0.0  0.0  132.628861  1.374434  1884.680458

In [15]:
row,n=X.shape

In [16]:
n

6

## Mathematical Formulation Implementation


##  Creation of Covariance Matrix for the datasets 

Notations Used for calculation of Covariance matrices 
1. Cxy=Covariance matrices between datasets x and y
2. Cyy=Covariance matrices between datasets y and y
3. Cxx=Covariance matrices between datasets x and x

Dot function returns the dot product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication.

In [17]:
Cxy=np.dot(X,Y.T)

In [18]:
Cxy=Cxy/n
Cxy

array([[1710.30071261,    0.        , 1169.78955539,  607.08658793,
           0.        ,    0.        , 1710.30071261, 1688.10890238,
        1710.30071261, 1169.78955539],
       [1695.12080798,    0.        , 1158.24161897,  600.24161972,
           0.        ,    0.        , 1695.12080798, 1673.99999775,
        1695.12080798, 1158.24161897],
       [1657.74670663,    0.        , 1134.31421807,  589.01941927,
           0.        ,    0.        , 1657.74670663, 1635.8843964 ,
        1657.74670663, 1134.31421807],
       [1782.64540052,    0.        , 1217.20334733,  630.1814839 ,
           0.        ,    0.        , 1782.64540052, 1761.06559029,
        1782.64540052, 1217.20334733],
       [1733.89177921,    0.        , 1184.20848867,  613.31472124,
           0.        ,    0.        , 1733.89177921, 1712.68130231,
        1733.89177921, 1184.20848867],
       [2115.89434403,    0.        , 1439.72042077,  741.70335395,
           0.        ,    0.        , 2115.89434403, 2094

In [19]:
Cxy[0]

array([1710.30071261,    0.        , 1169.78955539,  607.08658793,
          0.        ,    0.        , 1710.30071261, 1688.10890238,
       1710.30071261, 1169.78955539])

In [20]:
Cxy.shape

(10, 10)

In [21]:
Cyy=np.dot(Y,Y.T)
Cyy=Cyy/n
Cyy

array([[18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        , 16.66666667, 12.5       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [11.33333333,  0.        ,  8.16666667,  5.16666667,  0.        ,
         0.        , 11.33333333, 10.        , 11.16666667,  8.33333333],
       [ 8.        ,  0.        ,  5.16666667,  4.33333333,  0.        ,
         0.        ,  8.        ,  5.5       ,  7.5       ,  5.66666667],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        

In [22]:
Cxx=np.dot(X,X.T)
Cxx=Cxx/n
Cxx

array([[440475.08088602, 437392.59359429, 426593.61222376,
        460601.39539607, 447770.01898253, 550330.88763462,
        521206.31651111, 420689.29121013, 508351.43830122,
        511877.12904757],
       [437392.59359429, 434336.74286676, 423606.22296757,
        457387.0560252 , 444643.94196141, 546512.16119753,
        517576.48321974, 417743.25987134, 504806.96831281,
        508315.34235347],
       [426593.61222376, 423606.22296757, 413150.44171328,
        446082.01678638, 433655.63829703, 532974.19036135,
        504773.50278922, 407432.1783844 , 492325.60005641,
        495737.20794018],
       [460601.39539607, 457387.0560252 , 446082.01678638,
        481663.29963075, 468242.904456  , 575534.55851289,
        545052.71646843, 439907.98271898, 531602.30687942,
        535302.15746524],
       [447770.01898253, 444643.94196141, 433655.63829703,
        468242.904456  , 455196.7627372 , 559493.14288892,
        529864.241284  , 427653.58998487, 516789.69590172,
        520

W below is an diagonal matrices of size(n*n)

In [23]:
row,col=(n,n)
W=[]
for i in range(col):
    c=[]
    for j in range(row):
        if i==j:
            c.append(1/n)
        else:
            c.append(0)
    W.append(c)
W


[[0.16666666666666666, 0, 0, 0, 0, 0],
 [0, 0.16666666666666666, 0, 0, 0, 0],
 [0, 0, 0.16666666666666666, 0, 0, 0],
 [0, 0, 0, 0.16666666666666666, 0, 0],
 [0, 0, 0, 0, 0.16666666666666666, 0],
 [0, 0, 0, 0, 0, 0.16666666666666666]]

In [24]:
row,col=(n,n)
I=[]
for i in range(col):
    c1=[]
    for j in range(row):
        if i==j:
            c1.append(1)
        else:
            c1.append(0)
    I.append(c1)
I


[[1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1]]

I is identity matrix of size(n*n) made to perform subtraction of 2 matrices (I-W)

In [25]:
Diff=np.subtract(I,W)
Diff

array([[0.83333333, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.83333333, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.83333333, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.83333333, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.83333333,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.83333333]])

## Creation of Scatter Matrix Part for the datasets

Notations Used for calculation of Scatter matrices 
1. Swx=Between class scatter matrix for dataset x
2. Sbx=Within class scatter matrix for dataset x
3. Stx=Total scatter matrix for dataset x
4. Swy=Between class scatter matrix for dataset y
2. Sbx=Within class scatter matrix for dataset y
3. Stx=Total scatter matrix for dataset y

In [26]:
S=np.dot(X,Diff)
S

array([[8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.10959051e+02,
        1.09307730e+00, 1.35018482e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.05604051e+02,
        1.08562081e+00, 1.34111235e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.09311551e+02,
        1.09919251e+00, 1.30748203e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.07899051e+02,
        1.05906513e+00, 1.41254607e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.06052385e+02,
        1.10803057e+00, 1.37310020e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.09215718e+02,
        1.09200262e+00, 1.68934281e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.15369051e+02,
        1.14992133e+00, 1.59895873e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.07789051e+02,
        1.08803834e+00, 1.28938644e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.16285718e+02,
        1.14555124e+00, 

In [27]:
Sw=np.dot(S,X.T)
Sw

array([[2202375.40443012, 2186962.96797143, 2132968.06111879,
        2303006.97698037, 2238850.09491268, 2751654.4381731 ,
        2606031.58255556, 2103446.45605067, 2541757.19150612,
        2559385.64523785],
       [2186962.96797143, 2171683.71433381, 2118031.11483785,
        2286935.28012599, 2223219.70980706, 2732560.80598767,
        2587882.41609871, 2088716.29935669, 2524034.84156406,
        2541576.71176734],
       [2132968.06111879, 2118031.11483785, 2065752.2085664 ,
        2230410.0839319 , 2168278.19148515, 2664870.95180677,
        2523867.51394608, 2037160.89192199, 2461628.00028203,
        2478686.03970089],
       [2303006.97698037, 2286935.28012599, 2230410.0839319 ,
        2408316.49815373, 2341214.52227998, 2877672.79256445,
        2725263.58234214, 2199539.91359489, 2658011.53439712,
        2676510.78732618],
       [2238850.09491268, 2223219.70980706, 2168278.19148515,
        2341214.52227998, 2275983.81368599, 2797465.71444462,
        2649321.20642   

In [28]:
Sw.shape

(10, 10)

In [29]:
temp=Sw
temp
temp=temp/n
temp

array([[367062.56740502, 364493.82799524, 355494.67685313,
        383834.49616339, 373141.68248545, 458609.07302885,
        434338.59709259, 350574.40934178, 423626.19858435,
        426564.27420631],
       [364493.82799524, 361947.2857223 , 353005.18580631,
        381155.880021  , 370536.61830118, 455426.80099795,
        431313.73601645, 348119.38322611, 420672.47359401,
        423596.11862789],
       [355494.67685313, 353005.18580631, 344292.03476107,
        371735.01398865, 361379.69858086, 444145.15863446,
        420644.58565768, 339526.81532033, 410271.33338034,
        413114.33995015],
       [383834.49616339, 381155.880021  , 371735.01398865,
        401386.08302562, 390202.42038   , 479612.13209408,
        454210.59705702, 366589.98559915, 443001.92239952,
        446085.13122103],
       [373141.68248545, 370536.61830118, 361379.69858086,
        390202.42038   , 379330.63561433, 466244.28574077,
        441553.53440333, 356377.99165406, 430658.0799181 ,
        433

In [30]:
Sw=temp
Sw

array([[367062.56740502, 364493.82799524, 355494.67685313,
        383834.49616339, 373141.68248545, 458609.07302885,
        434338.59709259, 350574.40934178, 423626.19858435,
        426564.27420631],
       [364493.82799524, 361947.2857223 , 353005.18580631,
        381155.880021  , 370536.61830118, 455426.80099795,
        431313.73601645, 348119.38322611, 420672.47359401,
        423596.11862789],
       [355494.67685313, 353005.18580631, 344292.03476107,
        371735.01398865, 361379.69858086, 444145.15863446,
        420644.58565768, 339526.81532033, 410271.33338034,
        413114.33995015],
       [383834.49616339, 381155.880021  , 371735.01398865,
        401386.08302562, 390202.42038   , 479612.13209408,
        454210.59705702, 366589.98559915, 443001.92239952,
        446085.13122103],
       [373141.68248545, 370536.61830118, 361379.69858086,
        390202.42038   , 379330.63561433, 466244.28574077,
        441553.53440333, 356377.99165406, 430658.0799181 ,
        433

In [31]:
t=np.dot(X,W)
Sb=np.dot(t,X.T)
Sb

array([[440475.08088602, 437392.59359429, 426593.61222376,
        460601.39539607, 447770.01898254, 550330.88763462,
        521206.31651111, 420689.29121013, 508351.43830122,
        511877.12904757],
       [437392.59359429, 434336.74286676, 423606.22296757,
        457387.0560252 , 444643.94196141, 546512.16119753,
        517576.48321974, 417743.25987134, 504806.96831281,
        508315.34235347],
       [426593.61222376, 423606.22296757, 413150.44171328,
        446082.01678638, 433655.63829703, 532974.19036135,
        504773.50278922, 407432.1783844 , 492325.60005641,
        495737.20794018],
       [460601.39539607, 457387.0560252 , 446082.01678638,
        481663.29963075, 468242.904456  , 575534.55851289,
        545052.71646843, 439907.98271898, 531602.30687942,
        535302.15746524],
       [447770.01898253, 444643.94196141, 433655.63829703,
        468242.904456  , 455196.7627372 , 559493.14288892,
        529864.241284  , 427653.58998487, 516789.69590172,
        520

In [32]:
Sb=Sb/n
Sb

array([[ 73412.513481  ,  72898.76559905,  71098.93537063,
         76766.89923268,  74628.33649709,  91721.81460577,
         86867.71941852,  70114.88186836,  84725.23971687,
         85312.85484126],
       [ 72898.76559905,  72389.45714446,  70601.03716126,
         76231.1760042 ,  74107.32366024,  91085.36019959,
         86262.74720329,  69623.87664522,  84134.4947188 ,
         84719.22372558],
       [ 71098.93537063,  70601.03716126,  68858.40695221,
         74347.00279773,  72275.93971617,  88829.03172689,
         84128.91713154,  67905.36306407,  82054.26667607,
         82622.86799003],
       [ 76766.89923268,  76231.1760042 ,  74347.00279773,
         80277.21660512,  78040.484076  ,  95922.42641882,
         90842.1194114 ,  73317.99711983,  88600.3844799 ,
         89217.02624421],
       [ 74628.33649709,  74107.32366024,  72275.93971617,
         78040.484076  ,  75866.12712287,  93248.85714815,
         88310.70688067,  71275.59833081,  86131.61598362,
         86

In [33]:
Swx=Sw
Swx
Sbx=Sb


In [34]:
Swx

array([[367062.56740502, 364493.82799524, 355494.67685313,
        383834.49616339, 373141.68248545, 458609.07302885,
        434338.59709259, 350574.40934178, 423626.19858435,
        426564.27420631],
       [364493.82799524, 361947.2857223 , 353005.18580631,
        381155.880021  , 370536.61830118, 455426.80099795,
        431313.73601645, 348119.38322611, 420672.47359401,
        423596.11862789],
       [355494.67685313, 353005.18580631, 344292.03476107,
        371735.01398865, 361379.69858086, 444145.15863446,
        420644.58565768, 339526.81532033, 410271.33338034,
        413114.33995015],
       [383834.49616339, 381155.880021  , 371735.01398865,
        401386.08302562, 390202.42038   , 479612.13209408,
        454210.59705702, 366589.98559915, 443001.92239952,
        446085.13122103],
       [373141.68248545, 370536.61830118, 361379.69858086,
        390202.42038   , 379330.63561433, 466244.28574077,
        441553.53440333, 356377.99165406, 430658.0799181 ,
        433

In [35]:
Stx=np.dot(X,X.T)
Stx

array([[2642850.48531615, 2624355.56156571, 2559561.67334255,
        2763608.37237644, 2686620.11389521, 3301985.32580773,
        3127237.89906667, 2524135.7472608 , 3050108.62980734,
        3071262.77428542],
       [2624355.56156571, 2606020.45720057, 2541637.33780542,
        2744322.33615119, 2667863.65176847, 3279072.96718521,
        3105458.89931845, 2506459.55922802, 3028841.80987688,
        3049892.05412081],
       [2559561.67334255, 2541637.33780542, 2478902.65027967,
        2676492.10071828, 2601933.82978217, 3197845.14216813,
        3028641.01673529, 2444593.07030639, 2953953.60033843,
        2974423.24764107],
       [2763608.37237644, 2744322.33615119, 2676492.10071828,
        2889979.79778447, 2809457.42673597, 3453207.35107734,
        3270316.29881057, 2639447.89631386, 3189613.84127655,
        3211812.94479142],
       [2686620.11389521, 2667863.65176847, 2601933.82978217,
        2809457.42673597, 2731180.57642319, 3356958.85733354,
        3179185.447704  

In [36]:
Stx=Stx/n
Stx

array([[440475.08088602, 437392.59359429, 426593.61222376,
        460601.39539607, 447770.01898253, 550330.88763462,
        521206.31651111, 420689.29121013, 508351.43830122,
        511877.12904757],
       [437392.59359429, 434336.74286676, 423606.22296757,
        457387.0560252 , 444643.94196141, 546512.16119753,
        517576.48321974, 417743.25987134, 504806.96831281,
        508315.34235347],
       [426593.61222376, 423606.22296757, 413150.44171328,
        446082.01678638, 433655.63829703, 532974.19036135,
        504773.50278922, 407432.1783844 , 492325.60005641,
        495737.20794018],
       [460601.39539607, 457387.0560252 , 446082.01678638,
        481663.29963075, 468242.904456  , 575534.55851289,
        545052.71646843, 439907.98271898, 531602.30687942,
        535302.15746524],
       [447770.01898253, 444643.94196141, 433655.63829703,
        468242.904456  , 455196.7627372 , 559493.14288892,
        529864.241284  , 427653.58998487, 516789.69590172,
        520

In [37]:
S1=np.dot(Y,Diff)
S1

array([[0.        , 2.5       , 3.33333333, 3.33333333, 5.        ,
        5.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.83333333, 3.33333333, 3.33333333,
        3.33333333],
       [0.        , 0.        , 2.5       , 2.5       , 1.66666667,
        1.66666667],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 2.5       , 3.33333333, 3.33333333, 5.        ,
        5.        ],
       [0.        , 0.        , 0.        , 2.5       , 5.        ,
        5.        ],
       [0.        , 0.        , 2.5       , 3.33333333, 5.        ,
        5.        ],
       [0.        , 0.83333333, 1.66666667, 3.33333333, 3.33333333,
        3.33333333]])

In [38]:
Swy=np.dot(S1,Y.T)
Swy
Swy=Swy/n

In [39]:
S3=np.dot(Y,W)
Sby=np.dot(S3,Y.T)
Sby
Sby=Sby/n

In [40]:
Sty=np.dot(Y,Y.T)
Sty=Sty/n
Sty

array([[18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        , 16.66666667, 12.5       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [11.33333333,  0.        ,  8.16666667,  5.16666667,  0.        ,
         0.        , 11.33333333, 10.        , 11.16666667,  8.33333333],
       [ 8.        ,  0.        ,  5.16666667,  4.33333333,  0.        ,
         0.        ,  8.        ,  5.5       ,  7.5       ,  5.66666667],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        

### Use of Lagrangian multiplier technique for calculation of final projection vectors wx,wy  

Calculation of Transpose of Scatter matrices Stx,Sty 

In [41]:
Trans_Stx=np.linalg.inv(Stx)
Trans_Stx

array([[ 7.85905184e+09,  2.26526896e+10, -4.00661033e+09,
        -2.30127932e+08, -1.96656346e+10, -5.25073671e+09,
        -8.34773889e+09, -1.01604055e+10,  3.54387783e+09,
         1.36056348e+10],
       [-4.30536550e+10, -4.86032921e+10,  7.58917382e+09,
        -4.95768583e+09,  4.03760437e+10,  1.71624563e+10,
         3.31104452e+10,  5.16134151e+10, -7.02346448e+09,
        -4.62134370e+10],
       [ 5.66526374e+09, -9.14278743e+09, -4.65778006e+09,
         3.56703651e+09,  9.11053862e+09, -1.46871767e+09,
        -4.48925925e+09, -2.17418428e+09,  1.89021541e+09,
         1.69967445e+09],
       [ 9.78000336e+08,  3.54543985e+09,  1.82948875e+09,
         2.69615895e+09, -3.46558187e+09, -2.52429494e+09,
        -9.00237448e+08, -5.58628169e+09, -5.90554638e+08,
         4.01786279e+09],
       [ 2.38800175e+10,  3.75556908e+10,  6.86067088e+09,
         9.88893219e+08, -3.54193588e+10, -9.20829909e+09,
        -2.79958423e+10, -3.84976568e+10,  7.84812001e+09,
         3.

In [42]:
Trans_Sty=np.linalg.pinv(Sty)
Trans_Sty

array([[ 1.44908838e-01, -4.06903192e-18, -7.13430930e-02,
        -1.54012200e-01,  0.00000000e+00,  0.00000000e+00,
         1.44908838e-01, -1.94893952e-02, -1.60121442e-01,
         6.11809417e-04],
       [ 3.95746994e-17,  2.71262254e-32,  1.05234487e-16,
        -1.05400796e-16,  0.00000000e+00,  0.00000000e+00,
         3.95746994e-17,  8.03518816e-18, -2.01972074e-16,
         1.16431116e-16],
       [-7.13430930e-02,  1.25858494e-16,  8.56615798e-01,
        -1.11758066e-01,  0.00000000e+00,  0.00000000e+00,
        -7.13430930e-02, -9.66841055e-02, -8.86900546e-01,
         7.94934316e-01],
       [-1.54012200e-01, -9.42483094e-17, -1.11758066e-01,
         4.61540594e-01,  0.00000000e+00,  0.00000000e+00,
        -1.54012200e-01, -1.81678095e-01,  4.63926356e-01,
        -1.46824486e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.

# Solving Matrix A to make in form of eigen value 

We will find basically four values
1. a=Sbx*Trans_Stx
2. b=Cxy*Trans_Sty
3. c=Cxy*Trans_Stx
4. d=Sby*Trans_Sty

In [43]:
Sbx.shape

(10, 10)

In [44]:
Sby.shape

(10, 10)

In [45]:
Trans_Stx.shape

(10, 10)

In [46]:
Trans_Sty.shape

(10, 10)

In [47]:
a=np.dot(Sbx,Trans_Stx)
a

array([[ 0.125    , -0.0390625,  0.125    ,  0.15625  , -0.5      ,
         0.       ,  0.       ,  0.125    ,  0.25     ,  0.5      ],
       [ 0.125    , -0.2421875,  0.125    ,  0.0625   , -1.25     ,
         0.       ,  0.375    ,  0.75     ,  0.1875   ,  0.375    ],
       [-0.5      ,  0.03125  ,  0.125    ,  0.1875   , -1.       ,
        -0.03125  ,  0.       , -0.0625   ,  0.3125   ,  0.125    ],
       [ 0.75     , -0.1953125,  0.       ,  0.15625  , -0.75     ,
        -0.03125  ,  0.       ,  0.       ,  0.3125   ,  0.4375   ],
       [ 0.       , -1.       ,  0.       ,  0.03125  , -0.9375   ,
        -0.03125  , -0.25     ,  0.25     ,  0.1875   , -0.4375   ],
       [ 0.125    ,  0.921875 ,  0.25     ,  0.125    , -1.9375   ,
        -0.0625   , -0.125    ,  0.125    ,  0.4375   , -0.375    ],
       [-0.375    , -1.171875 ,  0.25     ,  0.15625  , -0.875    ,
         0.15625  ,  0.       ,  0.125    ,  0.4375   ,  0.0625   ],
       [ 0.125    ,  0.40625  ,  0.125   

In [48]:
b=np.dot(Cxy,Trans_Sty)
b

array([[ 1.26798819e+01,  1.57158451e-14, -5.99969695e+01,
        -6.23452479e+01,  0.00000000e+00,  0.00000000e+00,
         1.26798819e+01,  1.22016535e+02,  9.92507469e+01,
        -7.60792912e+01],
       [ 1.28570884e+01,  1.54823544e-14, -6.13108496e+01,
        -6.23216816e+01,  0.00000000e+00,  0.00000000e+00,
         1.28570884e+01,  1.21680352e+02,  9.99014160e+01,
        -7.71425304e+01],
       [ 1.21734298e+01,  1.52708317e-14, -5.74089281e+01,
        -6.02159000e+01,  0.00000000e+00,  0.00000000e+00,
         1.21734298e+01,  1.17966118e+02,  9.55834491e+01,
        -7.30405787e+01],
       [ 1.37302996e+01,  1.62138361e-14, -6.58106398e+01,
        -6.59223490e+01,  0.00000000e+00,  0.00000000e+00,
         1.37302996e+01,  1.28502694e+02,  1.06166295e+02,
        -8.23817976e+01],
       [ 1.32815750e+01,  1.57941565e-14, -6.35442324e+01,
        -6.39855695e+01,  0.00000000e+00,  0.00000000e+00,
         1.32815750e+01,  1.24799570e+02,  1.02875747e+02,
        -7.

In [49]:
c=np.dot(Cxy,Trans_Stx)
c

array([[ 1.64989006e+13,  1.36430467e+13, -1.41850080e+13,
         1.87173129e+12, -7.71402367e+12, -6.89640283e+12,
        -6.44454218e+11, -9.27839804e+12, -3.14329926e+12,
         9.84790751e+12],
       [ 1.63526007e+13,  1.35314403e+13, -1.40480472e+13,
         1.84289888e+12, -7.65752886e+12, -6.82765994e+12,
        -6.40729506e+11, -9.19594616e+12, -3.11640755e+12,
         9.75937942e+12],
       [ 1.59918681e+13,  1.32200003e+13, -1.37535916e+13,
         1.81914382e+12, -7.47216075e+12, -6.68752805e+12,
        -6.23847016e+11, -8.99333267e+12, -3.04630620e+12,
         9.54575415e+12],
       [ 1.71970379e+13,  1.42369648e+13, -1.47654016e+13,
         1.92922434e+12, -8.06156205e+12, -7.17475097e+12,
        -6.75254081e+11, -9.67068992e+12, -3.27804531e+12,
         1.02624770e+13],
       [ 1.67266809e+13,  1.38452013e+13, -1.43643771e+13,
         1.87954964e+12, -7.83806114e+12, -6.98043204e+12,
        -6.56282387e+11, -9.40623140e+12, -3.18813953e+12,
         9.

In [50]:
d=np.dot(Sby,Trans_Sty)
d

array([[ 8.06142709e-02, -1.15565426e-17, -1.19304904e-02,
        -3.68105705e-03,  0.00000000e+00,  0.00000000e+00,
         8.06142709e-02, -2.89916188e-04,  4.03247061e-03,
         1.63143746e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.19304904e-02,  1.33920275e-17,  9.25096199e-02,
         2.01974944e-02,  0.00000000e+00,  0.00000000e+00,
        -1.19304904e-02,  3.02303516e-02, -1.13857994e-02,
         7.15829424e-02],
       [-3.68105705e-03, -2.04832104e-17,  2.01974944e-02,
         1.01101682e-01,  0.00000000e+00,  0.00000000e+00,
        -3.68105705e-03, -5.28965263e-02,  5.39244109e-02,
         2.20863423e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.

Now my equation is of form of eigen value 
A.w=lambda.w
where A=block matrix like
 A=[ a      b
    c      d 
    ]
 
 
 w= resultant vector to be finded
 lambda= eigen value

## Eigen Value Decomposition of block matrix

Our Block matrices has 4 matrix inside it a,b,c,d as calculated previously so to make it in form of eigen equation we need to solve 

1.)  ((a)^(-1)*(b)*(d)^(-1)*(c))w=((lambda)*lambda))

2.) First find left equation (a)^(-1)*(b)*(d)^(-1)*(c) and it will become in form eigen equation which is (A).w=(lambda.lambda).w

3.) The decomposition of block matrices formula is refered through this link


4.) https://math.stackexchange.com/questions/222689/eigenvalue-decomposition-of-block-covariance-matrix-for-canonical-correlation-an

Some notations that would be used below

1.) Inv_a= Inverse of matrix a

2.) Inv_d=Inverse of matrix d

In [51]:
Inv_a=np.linalg.pinv(a)
Inv_d=np.linalg.pinv(d)
Inv_a
Inv_d

array([[ 2.90211375e+00, -6.81568367e-17, -4.29497654e-01,
        -1.32518054e-01, -1.02416142e-33,  0.00000000e+00,
         2.90211375e+00, -1.04369828e-02,  1.45168942e-01,
         5.87317485e-01],
       [-7.50838639e-16,  8.62193254e-32,  5.07705279e-16,
        -8.03329034e-16,  1.43702681e-31,  0.00000000e+00,
        -7.50838639e-16,  1.00136474e-15, -3.00128452e-16,
         3.17198610e-17],
       [-4.29497654e-01,  5.27494568e-16,  3.33034632e+00,
         7.27109799e-01,  1.00455293e-16,  0.00000000e+00,
        -4.29497654e-01,  1.08829266e+00, -4.09888778e-01,
         2.57698593e+00],
       [-1.32518054e-01, -2.64031266e-16,  7.27109799e-01,
         3.63966053e+00, -3.54289713e-16,  0.00000000e+00,
        -1.32518054e-01, -1.90427495e+00,  1.94127879e+00,
         7.95108323e-01],
       [ 7.25669322e-32, -5.72646008e-33,  1.71660088e-17,
        -6.05417605e-17,  1.26377050e-32,  0.00000000e+00,
         7.23957854e-32,  9.38970673e-17,  1.31701156e-17,
        -2.

Our F would be final matrix and will make equation in eigen form i.e. (F.w)=(lambda.lambda).w

Since R.H.S would be square of lambda so we will take sqaure root of matrix F

In [52]:
F1=np.dot(Inv_a,b)
F2=np.dot(F1,Inv_d)
F=np.dot(F2,c)
F

array([[-2.57338148e+14, -2.13488216e+14,  2.20420130e+14,
        -2.82881581e+13,  1.21199370e+14,  1.07003255e+14,
         1.01990462e+13,  1.44704692e+14,  4.90995534e+13,
        -1.53511526e+14],
       [-3.00308299e+15, -2.47896190e+15,  2.58705293e+15,
        -3.46310928e+14,  1.39861168e+15,  1.25875259e+15,
         1.16387142e+14,  1.68890947e+15,  5.71683638e+14,
        -1.79304164e+15],
       [ 1.46790584e+16,  1.21145104e+16, -1.26486619e+16,
         1.69622181e+15, -6.83304599e+15, -6.15492162e+15,
        -5.68337982e+14, -8.25543343e+15, -2.79411053e+15,
         8.76472092e+15],
       [-1.09857408e+16, -9.06666922e+15,  9.46593328e+15,
        -1.26915144e+15,  5.11410604e+15,  4.60613348e+15,
         4.25389263e+14,  6.17832467e+15,  2.09112315e+15,
        -6.55944852e+15],
       [ 9.32679683e+14,  7.70352620e+14, -8.02933047e+14,
         1.06965808e+14, -4.34946097e+14, -3.90570252e+14,
        -3.62426787e+13, -5.24522898e+14, -1.77597351e+14,
         5.

Making all values of F that are less than zero equal to zero so as to perform square root of matrix for all positive values

In [53]:
F[F<0]=0
F

array([[0.00000000e+00, 0.00000000e+00, 2.20420130e+14, 0.00000000e+00,
        1.21199370e+14, 1.07003255e+14, 1.01990462e+13, 1.44704692e+14,
        4.90995534e+13, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.58705293e+15, 0.00000000e+00,
        1.39861168e+15, 1.25875259e+15, 1.16387142e+14, 1.68890947e+15,
        5.71683638e+14, 0.00000000e+00],
       [1.46790584e+16, 1.21145104e+16, 0.00000000e+00, 1.69622181e+15,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 8.76472092e+15],
       [0.00000000e+00, 0.00000000e+00, 9.46593328e+15, 0.00000000e+00,
        5.11410604e+15, 4.60613348e+15, 4.25389263e+14, 6.17832467e+15,
        2.09112315e+15, 0.00000000e+00],
       [9.32679683e+14, 7.70352620e+14, 0.00000000e+00, 1.06965808e+14,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.56814217e+14],
       [0.00000000e+00, 0.00000000e+00, 3.22123636e+16, 0.00000000e+00,
   

In [54]:
F_Final=np.sqrt(F)
F_Final

array([[0.00000000e+00, 0.00000000e+00, 1.48465528e+07, 0.00000000e+00,
        1.10090585e+07, 1.03442378e+07, 3.19359456e+06, 1.20293263e+07,
        7.00710735e+06, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.08630802e+07, 0.00000000e+00,
        3.73980171e+07, 3.54789035e+07, 1.07882873e+07, 4.10963437e+07,
        2.39099067e+07, 0.00000000e+00],
       [1.21157164e+08, 1.10065937e+08, 0.00000000e+00, 4.11852135e+07,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 9.36200882e+07],
       [0.00000000e+00, 0.00000000e+00, 9.72930279e+07, 0.00000000e+00,
        7.15129781e+07, 6.78685014e+07, 2.06249670e+07, 7.86023197e+07,
        4.57288000e+07, 0.00000000e+00],
       [3.05398049e+07, 2.77552269e+07, 0.00000000e+00, 1.03424276e+07,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.35969112e+07],
       [0.00000000e+00, 0.00000000e+00, 1.79478031e+08, 0.00000000e+00,
   

Applying S.V.D which will give 3 output matrix U,D,V

In [55]:
U,D,V=np.linalg.svd(F_Final)
V

array([[-4.73777641e-18,  3.73651861e-17,  5.82617654e-01,
        -1.05480961e-16,  4.28386081e-01,  4.06396899e-01,
         1.23578534e-01,  4.70745409e-01,  2.73880816e-01,
        -1.28247062e-18],
       [-6.27710155e-01, -5.70242117e-01, -2.79976815e-18,
        -2.13395645e-01, -2.07626803e-18, -1.95077194e-18,
        -6.02247243e-19, -2.26920152e-18, -1.32150507e-18,
        -4.85042460e-01],
       [-7.97387198e-14,  7.92517075e-14, -4.02677037e-01,
        -7.36541158e-14,  7.07082859e-01, -4.08065979e-01,
         3.96524702e-01,  3.74578818e-02,  1.12837315e-01,
         4.24256067e-14],
       [-4.29596727e-02, -3.14735963e-01, -8.44879722e-14,
         9.48168788e-01,  3.70737281e-14, -5.46304246e-14,
         9.99407164e-15,  1.14769492e-13,  1.29058589e-15,
         8.46695877e-03],
       [-4.95716915e-11,  3.35827789e-11, -1.14468957e-01,
         8.62952033e-12,  7.24567553e-03, -4.11584419e-01,
        -6.91614602e-01,  4.80884294e-01,  3.28423753e-01,
         2.

In [56]:
V=V.T
V

array([[-4.73777641e-18, -6.27710155e-01, -7.97387198e-14,
        -4.29596727e-02, -4.95716915e-11,  4.06270009e-01,
        -4.82795710e-09,  6.62630446e-01, -1.15351363e-06,
         4.04134832e-07],
       [ 3.73651861e-17, -5.70242117e-01,  7.92517075e-14,
        -3.14735963e-01,  3.35827789e-11, -7.52256572e-01,
         7.50927695e-10, -9.93743017e-02,  1.72898307e-07,
        -6.06289519e-08],
       [ 5.82617654e-01, -2.79976815e-18, -4.02677037e-01,
        -8.44879722e-14, -1.14468957e-01,  6.82428350e-11,
        -1.29460334e-01, -1.26176949e-06, -6.32887535e-01,
         2.60764495e-01],
       [-1.05480961e-16, -2.13395645e-01, -7.36541158e-14,
         9.48168788e-01,  8.62952033e-12, -2.35424759e-01,
        -1.74112827e-11,  3.66482716e-03, -6.41193838e-09,
         2.22799385e-09],
       [ 4.28386081e-01, -2.07626803e-18,  7.07082859e-01,
         3.70737281e-14,  7.24567553e-03,  4.72332763e-11,
         5.29511869e-01, -2.88634977e-07, -1.84227621e-01,
        -4.

## Last Step: Calculation of Final Projection Vectors wx and wy

Formula to calculate wx, wy is

1.) wx=(Cxx)^(-1/2)*(U)

2.) wy=(Cyy)^(-1/2)*(V)

In [57]:
Cxxi=np.linalg.inv(Cxx)
Cxxi[Cxxi<0]=0
Cxx_sqrt=np.sqrt(Cxxi)
Cxx_sqrt

array([[ 88651.29352792, 150508.10465505,      0.        ,
             0.        ,      0.        ,      0.        ,
             0.        ,      0.        ,  59530.47819104,
        116643.19437344],
       [     0.        ,      0.        ,  87115.86434018,
             0.        , 200937.91000288, 131005.55833585,
        181962.75766916, 227185.8601941 ,      0.        ,
             0.        ],
       [ 75267.94628825,      0.        ,      0.        ,
         59724.67251904,  95449.14155122,      0.        ,
             0.        ,      0.        ,  43476.6076245 ,
         41227.10823651],
       [ 31272.99691067,  59543.59619569,  42772.52327425,
         51924.5505351 ,      0.        ,      0.        ,
             0.        ,      0.        ,      0.        ,
         63386.6136368 ],
       [154531.60675892, 193792.90688655,  82829.16684147,
         31446.67262997,      0.        ,      0.        ,
             0.        ,      0.        ,  88589.61568104,
        184

In [58]:
wx=np.dot(Cxx_sqrt,U)
wx

array([[ 4.22017482e+04, -7.33532836e+04,  7.65677914e+04,
        -4.64439170e+04,  3.80843080e+04,  1.04832076e+04,
        -1.08379765e+04,  3.74061512e+04, -1.46125585e+05,
         8.97230051e+04],
       [ 1.33821852e+05, -1.25185675e+05, -6.05093916e+04,
        -2.16358407e+04,  1.03212281e+05,  2.50490778e+05,
         1.32178560e+05,  3.51228427e+03,  2.43555479e+04,
        -1.43760883e+05],
       [ 3.25890529e+04, -5.64234278e+04,  5.18663548e+04,
        -6.21336961e+04,  5.23505688e+04,  5.41241774e+04,
        -5.16604142e+04, -4.89529954e+04,  8.37518901e+03,
         1.81938899e+04],
       [ 4.01828926e+04, -4.77334926e+04,  1.50334930e+04,
        -3.94951106e+04,  2.71629736e+04, -9.58272519e+03,
        -4.58328937e+04,  4.33792289e+04, -5.04145974e+04,
         5.85070800e+03],
       [ 7.15504209e+04, -1.67845506e+05,  1.26554601e+05,
        -7.93246027e+04,  7.69651147e+04, -1.23671394e+04,
        -4.11922027e+04,  7.93016919e+04, -1.83666092e+05,
         8.

In [59]:
Cyyi=np.linalg.pinv(Cyy)
Cyyi[Cyyi<0]=0
Cyy_sqrt=np.sqrt(Cyyi)
Cyy_sqrt

array([[3.80668935e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 3.80668935e-01, 0.00000000e+00,
        0.00000000e+00, 2.47347815e-02],
       [6.29084250e-09, 1.64700411e-16, 1.02583862e-08, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 6.29084250e-09, 2.83464075e-09,
        0.00000000e+00, 1.07903251e-08],
       [0.00000000e+00, 1.12186672e-08, 9.25535412e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 8.91590890e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.79367790e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        6.81121396e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
   

In [60]:
wy=np.dot(Cyy_sqrt,V)
wy

array([[ 4.70425091e-02, -2.50947175e-01,  1.50944636e-01,
        -1.61439845e-02, -2.63276194e-01,  1.66086816e-01,
        -2.20882790e-01,  2.33881884e-01,  4.22030136e-02,
         5.18355708e-03],
       [ 8.08852411e-09, -9.18259165e-09, -1.53016247e-09,
        -1.78891349e-10, -4.16197109e-09,  7.54308131e-09,
        -6.19134939e-09, -3.84133112e-09, -5.30640668e-09,
         1.12512954e-09],
       [ 5.39233270e-01, -4.32459445e-01, -3.72691857e-01,
         7.54905978e-03, -1.05945073e-01,  4.12094336e-01,
        -1.19820118e-01, -6.61842851e-01, -5.85758673e-01,
         2.41346370e-01],
       [ 1.86546084e-01, -1.44974128e-01,  7.68559098e-02,
         6.44155334e-01,  2.23696445e-01, -1.59939998e-01,
        -1.02178117e-01,  2.48999973e-03,  3.14822242e-01,
         5.13445782e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.

The final values wx, wy is hence calculated and these are our final projection vectors