# Data Science Project

##  Project Topic: Multiview Uncorrelated Linear Discriminant Analysis(MULDA) 

Prepared by 
1. Aadeesh Jain(0801CS171001) 
2. Harsh Pastaria (0801CS171027)
3. Kanishk Gupta(0801CS171031)

## Importing the required libraries

In [2]:
import numpy as np
import pandas as pd
import math
import os

# Importing Datasets

We are considering 2 datasets for multiview X,Y also these datasets uploaded in github for further info.

In [3]:
X=pd.read_csv('mfeat-mor',delim_whitespace=True,header=None)

In [4]:
X

0    1    2           3         4            5
0     1.0  0.0  0.0  133.150861  1.311693  1620.221779
1     1.0  0.0  0.0  126.724861  1.302745  1609.334822
2     1.0  0.0  0.0  131.173861  1.319031  1568.978435
3     1.0  0.0  0.0  129.478861  1.270878  1695.055281
4     1.0  0.0  0.0  127.262861  1.329637  1647.720235
...   ...  ...  ...         ...       ...          ...
1995  1.0  1.0  1.0  157.498861  1.655794  5326.025889
1996  1.0  1.0  1.0  152.404861  1.620345  5243.267754
1997  1.0  1.0  1.0  134.672861  1.541987  3766.763222
1998  1.0  1.0  1.0  142.926861  1.426381  4118.327320
1999  1.0  1.0  1.0  133.920861  1.564621  3808.021317

[2000 rows x 6 columns]

In [5]:
Y=df=pd.read_csv('mfeat-pix',delim_whitespace=True,header=None)

In [6]:
Y

0    1    2    3    4    5    6    7    8    9    ...  230  231  232  \
0       0    3    4    4    6    6    6    6    6    5  ...    4    4    4   
1       0    0    0    0    0    0    1    3    4    4  ...    2    4    4   
2       0    0    1    4    4    4    4    4    4    3  ...    1    3    4   
3       0    0    3    3    2    2    4    5    6    6  ...    4    4    4   
4       0    0    0    0    0    0    3    4    6    6  ...    4    4    4   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1995    0    0    0    1    3    4    5    6    4    4  ...    4    4    4   
1996    0    0    0    0    3    6    6    6    6    6  ...    4    4    4   
1997    0    0    0    2    4    4    4    6    4    4  ...    0    2    4   
1998    0    0    0    0    0    0    2    4    4    5  ...    3    4    4   
1999    0    0    1    5    6    6    6    6    6    6  ...    4    4    1   

      233  234  235  236  237  238  239  
0       4    4    3    0    0    0    0  
1       4    4    2    0    0    0    0  
2       4    4    4    4    2    1    0  
3       4    2    0    0    0    0    0  
4       4    3    1    0    0    0    0  
...   ...  ...  ...  ...  ...  ...  ...  
1995    4    4    4    4    0    0    0  
1996    3    0    0    0    0    0    0  
1997    4    4    1    0    0    0    0  
1998    4    4    2    0    0    0    0  
1999    0    0    0    0    0    0    0  

[2000 rows x 240 columns]

Calculating shape of each dataset by using shape function

In [7]:
Y.shape

(2000, 240)

Reducing dataset column and rows for better results


In [8]:
Y=Y[:10]
Y

0    1    2    3    4    5    6    7    8    9    ...  230  231  232  233  \
0    0    3    4    4    6    6    6    6    6    5  ...    4    4    4    4   
1    0    0    0    0    0    0    1    3    4    4  ...    2    4    4    4   
2    0    0    1    4    4    4    4    4    4    3  ...    1    3    4    4   
3    0    0    3    3    2    2    4    5    6    6  ...    4    4    4    4   
4    0    0    0    0    0    0    3    4    6    6  ...    4    4    4    4   
5    0    0    0    0    0    0    0    0    0    5  ...    4    4    2    0   
6    0    3    4    4    6    6    6    5    4    5  ...    4    4    4    4   
7    0    0    0    3    6    6    6    6    6    6  ...    4    4    4    4   
8    0    0    3    4    6    6    6    6    6    6  ...    4    4    4    4   
9    0    1    2    4    4    4    4    4    4    4  ...    2    2    3    3   

   234  235  236  237  238  239  
0    4    3    0    0    0    0  
1    4    2    0    0    0    0  
2    4    4    4    2    1    0  
3    2    0    0    0    0    0  
4    3    1    0    0    0    0  
5    0    0    0    0    0    0  
6    4    4    4    3    0    0  
7    3    0    0    0    0    0  
8    4    4    4    4    1    0  
9    2    2    2    2    1    0  

[10 rows x 240 columns]

In [9]:
X=X[:10]
X

0    1    2           3         4            5
0  1.0  0.0  0.0  133.150861  1.311693  1620.221779
1  1.0  0.0  0.0  126.724861  1.302745  1609.334822
2  1.0  0.0  0.0  131.173861  1.319031  1568.978435
3  1.0  0.0  0.0  129.478861  1.270878  1695.055281
4  1.0  0.0  0.0  127.262861  1.329637  1647.720235
5  1.0  0.0  0.0  131.058861  1.310403  2027.211367
6  1.0  0.0  0.0  138.442861  1.379906  1918.750472
7  1.0  0.0  0.0  129.346861  1.305646  1547.263727
8  1.0  0.0  0.0  139.542861  1.374661  1871.055934
9  1.0  0.0  0.0  132.628861  1.374434  1884.680458

In [10]:
Y.drop(Y.iloc[:, 7:], inplace = True, axis = 1) 
Y

c:\users\khushi\appdata\local\programs\python\python38-32\lib\site-packages\pandas\core\frame.py:4162: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


0  1  2  3  4  5  6
0  0  3  4  4  6  6  6
1  0  0  0  0  0  0  1
2  0  0  1  4  4  4  4
3  0  0  3  3  2  2  4
4  0  0  0  0  0  0  3
5  0  0  0  0  0  0  0
6  0  3  4  4  6  6  6
7  0  0  0  3  6  6  6
8  0  0  3  4  6  6  6
9  0  1  2  4  4  4  4

In [11]:
Y.drop(Y.iloc[:, 6:], inplace = True, axis = 1) 
Y

c:\users\khushi\appdata\local\programs\python\python38-32\lib\site-packages\pandas\core\frame.py:4162: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


0  1  2  3  4  5
0  0  3  4  4  6  6
1  0  0  0  0  0  0
2  0  0  1  4  4  4
3  0  0  3  3  2  2
4  0  0  0  0  0  0
5  0  0  0  0  0  0
6  0  3  4  4  6  6
7  0  0  0  3  6  6
8  0  0  3  4  6  6
9  0  1  2  4  4  4

In [12]:
X

0    1    2           3         4            5
0  1.0  0.0  0.0  133.150861  1.311693  1620.221779
1  1.0  0.0  0.0  126.724861  1.302745  1609.334822
2  1.0  0.0  0.0  131.173861  1.319031  1568.978435
3  1.0  0.0  0.0  129.478861  1.270878  1695.055281
4  1.0  0.0  0.0  127.262861  1.329637  1647.720235
5  1.0  0.0  0.0  131.058861  1.310403  2027.211367
6  1.0  0.0  0.0  138.442861  1.379906  1918.750472
7  1.0  0.0  0.0  129.346861  1.305646  1547.263727
8  1.0  0.0  0.0  139.542861  1.374661  1871.055934
9  1.0  0.0  0.0  132.628861  1.374434  1884.680458

In [13]:
row,n=X.shape
n

6

## Mathematical Formulation Implementation

Notations Used for calculation of Covariance matrices 
1. Cxy=Covariance matrices between datasets x and y
2. Cyy=Covariance matrices between datasets y and y
3. Cxx=Covariance matrices between datasets x and x

Dot function returns the dot product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication.

In [14]:
Cxy=np.dot(X,Y.T)
Cxy=Cxy/n
Cxy

array([[1710.30071261,    0.        , 1169.78955539,  607.08658793,
           0.        ,    0.        , 1710.30071261, 1688.10890238,
        1710.30071261, 1169.78955539],
       [1695.12080798,    0.        , 1158.24161897,  600.24161972,
           0.        ,    0.        , 1695.12080798, 1673.99999775,
        1695.12080798, 1158.24161897],
       [1657.74670663,    0.        , 1134.31421807,  589.01941927,
           0.        ,    0.        , 1657.74670663, 1635.8843964 ,
        1657.74670663, 1134.31421807],
       [1782.64540052,    0.        , 1217.20334733,  630.1814839 ,
           0.        ,    0.        , 1782.64540052, 1761.06559029,
        1782.64540052, 1217.20334733],
       [1733.89177921,    0.        , 1184.20848867,  613.31472124,
           0.        ,    0.        , 1733.89177921, 1712.68130231,
        1733.89177921, 1184.20848867],
       [2115.89434403,    0.        , 1439.72042077,  741.70335395,
           0.        ,    0.        , 2115.89434403, 2094

In [15]:
Cyy=np.dot(Y,Y.T)
Cyy=Cyy/n
Cyy

array([[18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        , 16.66666667, 12.5       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [11.33333333,  0.        ,  8.16666667,  5.16666667,  0.        ,
         0.        , 11.33333333, 10.        , 11.16666667,  8.33333333],
       [ 8.        ,  0.        ,  5.16666667,  4.33333333,  0.        ,
         0.        ,  8.        ,  5.5       ,  7.5       ,  5.66666667],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        

In [16]:
Cxx=np.dot(X,X.T)
Cxx=Cxx/n
Cxx

array([[440475.08088602, 437392.59359429, 426593.61222376,
        460601.39539607, 447770.01898253, 550330.88763462,
        521206.31651111, 420689.29121013, 508351.43830122,
        511877.12904757],
       [437392.59359429, 434336.74286676, 423606.22296757,
        457387.0560252 , 444643.94196141, 546512.16119753,
        517576.48321974, 417743.25987134, 504806.96831281,
        508315.34235347],
       [426593.61222376, 423606.22296757, 413150.44171328,
        446082.01678638, 433655.63829703, 532974.19036135,
        504773.50278922, 407432.1783844 , 492325.60005641,
        495737.20794018],
       [460601.39539607, 457387.0560252 , 446082.01678638,
        481663.29963075, 468242.904456  , 575534.55851289,
        545052.71646843, 439907.98271898, 531602.30687942,
        535302.15746524],
       [447770.01898253, 444643.94196141, 433655.63829703,
        468242.904456  , 455196.7627372 , 559493.14288892,
        529864.241284  , 427653.58998487, 516789.69590172,
        520

W below is an diagonal matrices of size(n*n)

In [17]:
row,col=(n,n)
W=[]
for i in range(col):
    c=[]
    for j in range(row):
        if i==j:
            c.append(1/n)
        else:
            c.append(0)
    W.append(c)
W

[[0.16666666666666666, 0, 0, 0, 0, 0],
 [0, 0.16666666666666666, 0, 0, 0, 0],
 [0, 0, 0.16666666666666666, 0, 0, 0],
 [0, 0, 0, 0.16666666666666666, 0, 0],
 [0, 0, 0, 0, 0.16666666666666666, 0],
 [0, 0, 0, 0, 0, 0.16666666666666666]]

In [18]:
row,col=(n,n)
I=[]
for i in range(col):
    c1=[]
    for j in range(row):
        if i==j:
            c1.append(1)
        else:
            c1.append(0)
    I.append(c1)
I

[[1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1]]

I is identity matrix of size(n*n) made to perform subtraction of 2 matrices (I-W)

In [19]:
Diff=np.subtract(I,W)
Diff

array([[0.83333333, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.83333333, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.83333333, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.83333333, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.83333333,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.83333333]])

## Creation of Scatter Matrix Part for the datasets

Notations Used for calculation of Scatter matrices 
1. Swx=Between class scatter matrix for dataset x
2. Sbx=Within class scatter matrix for dataset x
3. Stx=Total scatter matrix for dataset x
4. Swy=Between class scatter matrix for dataset y
2. Sbx=Within class scatter matrix for dataset y
3. Stx=Total scatter matrix for dataset y

In [20]:
S=np.dot(X,Diff)
S

array([[8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.10959051e+02,
        1.09307730e+00, 1.35018482e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.05604051e+02,
        1.08562081e+00, 1.34111235e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.09311551e+02,
        1.09919251e+00, 1.30748203e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.07899051e+02,
        1.05906513e+00, 1.41254607e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.06052385e+02,
        1.10803057e+00, 1.37310020e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.09215718e+02,
        1.09200262e+00, 1.68934281e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.15369051e+02,
        1.14992133e+00, 1.59895873e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.07789051e+02,
        1.08803834e+00, 1.28938644e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.16285718e+02,
        1.14555124e+00, 

In [21]:
Sw=np.dot(S,X.T)
Sw=Sw/n
Sw

array([[367062.56740502, 364493.82799524, 355494.67685313,
        383834.49616339, 373141.68248545, 458609.07302885,
        434338.59709259, 350574.40934178, 423626.19858435,
        426564.27420631],
       [364493.82799524, 361947.2857223 , 353005.18580631,
        381155.880021  , 370536.61830118, 455426.80099795,
        431313.73601645, 348119.38322611, 420672.47359401,
        423596.11862789],
       [355494.67685313, 353005.18580631, 344292.03476107,
        371735.01398865, 361379.69858086, 444145.15863446,
        420644.58565768, 339526.81532033, 410271.33338034,
        413114.33995015],
       [383834.49616339, 381155.880021  , 371735.01398865,
        401386.08302562, 390202.42038   , 479612.13209408,
        454210.59705702, 366589.98559915, 443001.92239952,
        446085.13122103],
       [373141.68248545, 370536.61830118, 361379.69858086,
        390202.42038   , 379330.63561433, 466244.28574077,
        441553.53440333, 356377.99165406, 430658.0799181 ,
        433

In [22]:
t=np.dot(X,W)
Sb=np.dot(t,X.T)
Sb=Sb/n
Sb

array([[ 73412.513481  ,  72898.76559905,  71098.93537063,
         76766.89923268,  74628.33649709,  91721.81460577,
         86867.71941852,  70114.88186836,  84725.23971687,
         85312.85484126],
       [ 72898.76559905,  72389.45714446,  70601.03716126,
         76231.1760042 ,  74107.32366024,  91085.36019959,
         86262.74720329,  69623.87664522,  84134.4947188 ,
         84719.22372558],
       [ 71098.93537063,  70601.03716126,  68858.40695221,
         74347.00279773,  72275.93971617,  88829.03172689,
         84128.91713154,  67905.36306407,  82054.26667607,
         82622.86799003],
       [ 76766.89923268,  76231.1760042 ,  74347.00279773,
         80277.21660512,  78040.484076  ,  95922.42641882,
         90842.1194114 ,  73317.99711983,  88600.3844799 ,
         89217.02624421],
       [ 74628.33649709,  74107.32366024,  72275.93971617,
         78040.484076  ,  75866.12712287,  93248.85714815,
         88310.70688067,  71275.59833081,  86131.61598362,
         86

In [23]:
Swx=Sw
Sbx=Sb

In [24]:
Stx=np.dot(X,X.T)
Stx=Stx/n
Stx

array([[440475.08088602, 437392.59359429, 426593.61222376,
        460601.39539607, 447770.01898253, 550330.88763462,
        521206.31651111, 420689.29121013, 508351.43830122,
        511877.12904757],
       [437392.59359429, 434336.74286676, 423606.22296757,
        457387.0560252 , 444643.94196141, 546512.16119753,
        517576.48321974, 417743.25987134, 504806.96831281,
        508315.34235347],
       [426593.61222376, 423606.22296757, 413150.44171328,
        446082.01678638, 433655.63829703, 532974.19036135,
        504773.50278922, 407432.1783844 , 492325.60005641,
        495737.20794018],
       [460601.39539607, 457387.0560252 , 446082.01678638,
        481663.29963075, 468242.904456  , 575534.55851289,
        545052.71646843, 439907.98271898, 531602.30687942,
        535302.15746524],
       [447770.01898253, 444643.94196141, 433655.63829703,
        468242.904456  , 455196.7627372 , 559493.14288892,
        529864.241284  , 427653.58998487, 516789.69590172,
        520

In [25]:
S1=np.dot(Y,Diff)
S1

array([[0.        , 2.5       , 3.33333333, 3.33333333, 5.        ,
        5.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.83333333, 3.33333333, 3.33333333,
        3.33333333],
       [0.        , 0.        , 2.5       , 2.5       , 1.66666667,
        1.66666667],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 2.5       , 3.33333333, 3.33333333, 5.        ,
        5.        ],
       [0.        , 0.        , 0.        , 2.5       , 5.        ,
        5.        ],
       [0.        , 0.        , 2.5       , 3.33333333, 5.        ,
        5.        ],
       [0.        , 0.83333333, 1.66666667, 3.33333333, 3.33333333,
        3.33333333]])

In [26]:
Swy=np.dot(S1,Y.T)
Swy
Swy=Swy/n

In [27]:
S3=np.dot(Y,W)
Sby=np.dot(S3,Y.T)
Sby
Sby=Sby/n

In [28]:
Sty=np.dot(Y,Y.T)
Sty=Sty/n
Sty

array([[18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        , 16.66666667, 12.5       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [11.33333333,  0.        ,  8.16666667,  5.16666667,  0.        ,
         0.        , 11.33333333, 10.        , 11.16666667,  8.33333333],
       [ 8.        ,  0.        ,  5.16666667,  4.33333333,  0.        ,
         0.        ,  8.        ,  5.5       ,  7.5       ,  5.66666667],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        

### Calculating sigma : σ ← tr(Stx )/tr(Sty )


In [29]:
sigma1= Stx.trace()
sigma2= Sty.trace()
sigma= sigma1/sigma2
sigma

57663.851948383446

Trace function above determines the trace of the matrix Stx, Sty 

In [30]:
r,c=Stx.shape

Iu below is an diagonal matrix of size (r.c) i.e. (10*10) in this case.

In [31]:
Iu=[]

for i in range(c):
    c1=[]
    for j in range(r):
        if i==j:
            c1.append(1)
        else:
            c1.append(0)
    Iu.append(c1)
Iu

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

Notations used in below part of the code will be

1.) Dx,Dy= Empty Matrices of shape (r,c) 

In [32]:
d = Stx.shape[0]

Dx = [ [ 0 for i in range(r) ] for j in range(c) ]
Dy = [ [ 0 for i in range(r) ] for j in range(c) ]


### Calculation of matrix Px,Py can be done using following formula 



Px = I−StxDx(Transpose)*(DxStxDx(Transpose)^(-1))*Dx

Py = I−StyDy(Transpose)*(DyStyDy(Transpose)^(-1))*Dy



### Calculation of rth vector pair wxr,wyr 

The value of wxr,wyr can be find by each time in loop running through variable r by finding eigen value of matrix wx 
 
and taking maximum of all values coming everytime through loop

### Finding value of matrix Dx,Dy

The value of Dx and Dy can be find by appending wxr to Dx and wyr to Dy as the last column

In [33]:

for u in range(0,d):
    #calculating Px
    p=np.dot(Stx,np.transpose(Dx))
    p1=np.dot((np.dot(Dx,Stx)),np.transpose(Dx))
    p1_inv=np.linalg.pinv(p1)

    Px=np.dot((np.dot(p,p1_inv)),Dx)
    Px = Iu - Px
    #Calculating Py
    P=np.dot(Sty,np.transpose(Dy))
    P1=np.dot((np.dot(Dy,Sty)),np.transpose(Dy))
    P1_inv=np.linalg.pinv(P1)

    Py=np.dot((np.dot(P,P1_inv)),Dy)
    Py= Iu-Py
    
    #Wx and Wy
    A = Sty*Px*Sbx
    A = sigma*A
    B = Sty*Px*Cxy
    B = sigma*B
    C = Stx*Py*Cxy
    D =Stx*Py*Sby
    
    Inv_a=np.linalg.pinv(A)
    Inv_d=np.linalg.pinv(D)

    F1=np.dot(Inv_a,B)
    F2=np.dot(F1,Inv_d)
    F=np.dot(F2,C)
    F[F<0]=0
    F_Final=np.sqrt(F)

    U,D,V=np.linalg.svd(F_Final)
    V=V.T

    Cxxi=np.linalg.inv(Cxx)
    Cxxi[Cxxi<0]=0
    Cxx_sqrt=np.sqrt(Cxxi)
    wx=np.dot(Cxx_sqrt,U)

    Cyyi=np.linalg.pinv(Cyy)
    Cyyi[Cyyi<0]=0
    Cyy_sqrt=np.sqrt(Cyyi)
    wy=np.dot(Cyy_sqrt,V)
    
    #rth vector pair
    wValues, vVectors = np.linalg.eig(wx)
    index = np.argmax(wValues, axis=0)
    
    l = [0]*r
    for i in range (0,r):
        l[i] = wx[i][index]

     # Finding matrix Dx,Dy
    for i in range(len(l)):
        Dx[i][u]=l[i]
        
    wValuesY, vVectorsY = np.linalg.eig(wy)
    indexY = np.argmax(wValuesY, axis=0)
    l1 = [0]*r
    for i in range (0,r):
        l1[i] = wy[i][indexY]

    for i in range(len(l1)):
        Dy[i][u]=l1[i] 
Dx

[[0.0,
  -0.0018849130177919647,
  -0.0004754517935415592,
  -51880.62692520769,
  -40201.06918308129,
  -30367.709688872397,
  -24786.41859698426,
  127281.89876837953,
  2008.730462586709,
  -0.0007206747731949507],
 [227185.86019409596,
  -227185.86101164136,
  -227185.86019409596,
  -235267.90752793394,
  131724.19539216982,
  -241788.63873829815,
  -251720.93995497326,
  -394.11833140199747,
  157544.934091083,
  131005.55891347998],
 [0.0,
  -0.00038834743779278183,
  2.842315822510363e-11,
  -44048.40659630357,
  -28452.066368953012,
  -42880.688647034374,
  -38237.561647802766,
  59150.300027817255,
  2839.602406872362,
  -0.00023736965604660945],
 [0.0,
  -0.00074570481580106,
  -0.00018809692873728948,
  -37658.07816713861,
  -26317.58235541152,
  -41326.49228109437,
  -38727.81802957239,
  48819.48550636012,
  -6358.26078328651,
  -0.00014871764831575398],
 [0.0,
  -0.002426998286874863,
  -0.0006121875617882608,
  -127919.04203154726,
  -100127.15725350408,
  -92428.1799924

In [34]:
temp = np.array(Dx)
temp.reshape(r,c)

array([[ 0.00000000e+00, -1.88491302e-03, -4.75451794e-04,
        -5.18806269e+04, -4.02010692e+04, -3.03677097e+04,
        -2.47864186e+04,  1.27281899e+05,  2.00873046e+03,
        -7.20674773e-04],
       [ 2.27185860e+05, -2.27185861e+05, -2.27185860e+05,
        -2.35267908e+05,  1.31724195e+05, -2.41788639e+05,
        -2.51720940e+05, -3.94118331e+02,  1.57544934e+05,
         1.31005559e+05],
       [ 0.00000000e+00, -3.88347438e-04,  2.84231582e-11,
        -4.40484066e+04, -2.84520664e+04, -4.28806886e+04,
        -3.82375616e+04,  5.91503000e+04,  2.83960241e+03,
        -2.37369656e-04],
       [ 0.00000000e+00, -7.45704816e-04, -1.88096929e-04,
        -3.76580782e+04, -2.63175824e+04, -4.13264923e+04,
        -3.87278180e+04,  4.88194855e+04, -6.35826078e+03,
        -1.48717648e-04],
       [ 0.00000000e+00, -2.42699829e-03, -6.12187562e-04,
        -1.27919042e+05, -1.00127157e+05, -9.24281800e+04,
        -8.13769277e+04,  1.97814244e+05, -2.93494764e+04,
        -7.

## Finding value of Wx and Wy

The feature extraction Wx and Wy can be finded just assigning Dx to be wxr and Dy to be wyr

In [35]:
Wx = temp
temp1 = np.array(Dy)
temp1.reshape(r,c)
Wy = temp1
Wy.shape

(10, 10)

## Finding Combined Feature Extraction Z

Res1 is finded out by multilplying Wy by X and similiarly Res2 by multiplying Wx with Y

Z is the combined vector pair of Res1 and Res2

In [36]:
Res1 = Wy.dot(X)
Res2 = Wx.dot(Y)


Z=[Res1,
   Res2
  ]

In [37]:
Z= [[0]*1]*2
Z[0] = Res1
Z[1] = Res2

In [38]:
Z

[array([[-1.10197408e+00,  0.00000000e+00,  0.00000000e+00,
         -1.39719128e+02, -1.41636520e+00, -1.73556455e+03],
        [-2.09750205e-08,  0.00000000e+00,  0.00000000e+00,
         -2.70871503e-06, -2.76042161e-08, -3.75690471e-05],
        [ 9.90744825e-03,  0.00000000e+00,  0.00000000e+00,
         -8.72035186e-01, -3.13331977e-02, -3.14983263e+02],
        [-1.94481241e-03,  0.00000000e+00,  0.00000000e+00,
         -5.00784101e+00, -4.35034693e-02,  9.32322143e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-1.10197408e+00,  0.00000000e+00,  0.00000000e+00,
         -1.39719128e+02, -1.41636520e+00, -1.73556455e+03],
        [-4.29274695e-01,  0.00000000e+00,  0.00000000e+00,
         -5.96783537e+01, -5.86612029e-01, -7.32325012e+02],
        [-1.84264487e-01,  0.000

Hence the final Value of Z is finded out which will be basically output of fit function and it ends the implementation of MULDA Algorithm.. 