In [4]:
from Lpcca import LPCCA    #LPCCA is the class present in folder lpcca.py
import pandas as pd
import numpy as np

In [5]:
x=pd.read_csv(r'mfeat-mor.csv',delim_whitespace=True,header=None)
y=pd.read_csv(r'mfeat-fou.csv',delim_whitespace=True,header=None)

In [6]:
print("Enter the k value (K is the number of neighbors to consider):")
k=int(input())

Enter the k value (K is the number of neighbors to consider):
5


In [7]:
lpcca=LPCCA(x,y,k)
X_new,Y_new=lpcca.fit_transform()
print("Reduced X :")
print(X_new)
print("Reduced Y :")
print(Y_new)

Reduced X :
[[ -6.57913273  -0.64169267   0.21302821  -1.64987656  -0.42263972
    0.38913911]
 [ -6.55214617  -0.61488357   0.22061729  -1.63455002  -0.43883368
    0.37831766]
 [ -6.37086653  -0.63362439   0.20032145  -1.5967536   -0.40040974
    0.38047697]
 ...
 [-15.66945001  -0.73164845   0.81626925  -3.81473014  -1.64039035
    0.63704735]
 [-17.10676291  -0.76615182   0.91193808  -4.17536977  -1.81160299
    0.6882749 ]
 [-15.84783143  -0.7275732    0.83086717  -3.85606964  -1.6663296
    0.64066895]]
Reduced Y :
[[5.33598167 0.90202708 0.9545263  ... 0.54614376 0.48841677 0.24411812]
 [5.01283454 0.77829964 0.75451309 ... 0.57678368 0.44566373 0.24750507]
 [4.92272159 0.81200191 0.78969627 ... 0.55274817 0.44565296 0.22887503]
 ...
 [5.80149775 1.49736941 1.89027285 ... 0.47465602 0.68954726 0.21923036]
 [5.3290344  1.39161786 1.78152749 ... 0.49538159 0.67017366 0.19758505]
 [4.93363816 1.32722936 1.7139352  ... 0.48279868 0.63046585 0.17674973]]


## Example 1

In [8]:
X = [[0., 0., 1.], [1.,0.,0.], [2.,2.,2.], [3.,5.,4.]]
Y = [[0.1, -0.2], [0.9, 1.1], [6.2, 5.9], [11.9, 12.3]]
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [9]:
lpcca=LPCCA(X,Y,4)
X_new,Y_new=lpcca.fit_transform()
print("Reduced X :")
print(X_new)
print("Reduced Y :")
print(Y_new)

Reduced X :
[[ 0.86537029  1.24428534  0.14600908]
 [ 0.78912431  1.15294729 -0.04861639]
 [ 6.65602742  2.38296086  0.07179918]
 [14.19644965  2.40722223  0.13072165]]
Reduced Y :
[[  0.08082053  -0.2573569 ]
 [ -1.72612779   0.1657403 ]
 [-10.47163744  -0.29415229]
 [-20.92435811   0.27055708]]


## Example 2

In [10]:
X = [[0.3, 0.2, 1.5], [1.3,0.2,0.5], [2.3,2.2,2.5], [3.3,5.2,4.5]]
Y = [[0.1, -0.2], [0.9, 1.1], [6.2, 5.9], [11.9, 12.3]]
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [11]:
lpcca=LPCCA(X,Y,4)
X_new,Y_new=lpcca.fit_transform()
print("Reduced X :")
print(X_new)
print("Reduced Y :")
print(Y_new)

Reduced X :
[[ 1.86949654e+00  1.97116176e+00  1.92130082e-01]
 [ 1.79325057e+00  1.87982371e+00 -2.49538617e-03]
 [ 7.66015368e+00  3.10983728e+00  1.17920182e-01]
 [ 1.52005759e+01  3.13409865e+00  1.76842651e-01]]
Reduced Y :
[[  0.08082053  -0.2573569 ]
 [ -1.72612779   0.1657403 ]
 [-10.47163744  -0.29415229]
 [-20.92435811   0.27055708]]
