# Data Science Project




            
 


##  Project Topic: Multiview Linear Discriminant Analysis(MLDA) 

Prepared by 
1. Aadeesh Jain(0801CS171001) 
2. Harsh Pastaria (0801CS171027)
3. Kanishk Gupta(0801CS171031)
            

## Importing the required libraries

In [1]:


import numpy as np
import pandas as pd
import math

# Importing Datasets

In [48]:
X=pd.read_csv('mfeat-mor',delim_whitespace=True,header=None)

We are considering 2 datasets for multiview X,Y also these datasets uploaded in github for further info.

In [49]:
X

0    1    2           3         4            5
0     1.0  0.0  0.0  133.150861  1.311693  1620.221779
1     1.0  0.0  0.0  126.724861  1.302745  1609.334822
2     1.0  0.0  0.0  131.173861  1.319031  1568.978435
3     1.0  0.0  0.0  129.478861  1.270878  1695.055281
4     1.0  0.0  0.0  127.262861  1.329637  1647.720235
...   ...  ...  ...         ...       ...          ...
1995  1.0  1.0  1.0  157.498861  1.655794  5326.025889
1996  1.0  1.0  1.0  152.404861  1.620345  5243.267754
1997  1.0  1.0  1.0  134.672861  1.541987  3766.763222
1998  1.0  1.0  1.0  142.926861  1.426381  4118.327320
1999  1.0  1.0  1.0  133.920861  1.564621  3808.021317

[2000 rows x 6 columns]

Impritjg

In [50]:
Y=df=pd.read_csv('mfeat-pix',delim_whitespace=True,header=None)

In [51]:
Y

0    1    2    3    4    5    6    7    8    9    ...  230  231  232  \
0       0    3    4    4    6    6    6    6    6    5  ...    4    4    4   
1       0    0    0    0    0    0    1    3    4    4  ...    2    4    4   
2       0    0    1    4    4    4    4    4    4    3  ...    1    3    4   
3       0    0    3    3    2    2    4    5    6    6  ...    4    4    4   
4       0    0    0    0    0    0    3    4    6    6  ...    4    4    4   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1995    0    0    0    1    3    4    5    6    4    4  ...    4    4    4   
1996    0    0    0    0    3    6    6    6    6    6  ...    4    4    4   
1997    0    0    0    2    4    4    4    6    4    4  ...    0    2    4   
1998    0    0    0    0    0    0    2    4    4    5  ...    3    4    4   
1999    0    0    1    5    6    6    6    6    6    6  ...    4    4    1   

      233  234  235  236  237  238  239  
0       4    4    3    0    0    0    0  
1       4    4    2    0    0    0    0  
2       4    4    4    4    2    1    0  
3       4    2    0    0    0    0    0  
4       4    3    1    0    0    0    0  
...   ...  ...  ...  ...  ...  ...  ...  
1995    4    4    4    4    0    0    0  
1996    3    0    0    0    0    0    0  
1997    4    4    1    0    0    0    0  
1998    4    4    2    0    0    0    0  
1999    0    0    0    0    0    0    0  

[2000 rows x 240 columns]

Calculating shape of each dataset by using shape function

In [52]:
Y.shape

(2000, 240)

Reducing dataset column and rows for better results

In [53]:
Y=Y[:10]

In [54]:
Y

0    1    2    3    4    5    6    7    8    9    ...  230  231  232  233  \
0    0    3    4    4    6    6    6    6    6    5  ...    4    4    4    4   
1    0    0    0    0    0    0    1    3    4    4  ...    2    4    4    4   
2    0    0    1    4    4    4    4    4    4    3  ...    1    3    4    4   
3    0    0    3    3    2    2    4    5    6    6  ...    4    4    4    4   
4    0    0    0    0    0    0    3    4    6    6  ...    4    4    4    4   
5    0    0    0    0    0    0    0    0    0    5  ...    4    4    2    0   
6    0    3    4    4    6    6    6    5    4    5  ...    4    4    4    4   
7    0    0    0    3    6    6    6    6    6    6  ...    4    4    4    4   
8    0    0    3    4    6    6    6    6    6    6  ...    4    4    4    4   
9    0    1    2    4    4    4    4    4    4    4  ...    2    2    3    3   

   234  235  236  237  238  239  
0    4    3    0    0    0    0  
1    4    2    0    0    0    0  
2    4    4    4    2    1    0  
3    2    0    0    0    0    0  
4    3    1    0    0    0    0  
5    0    0    0    0    0    0  
6    4    4    4    3    0    0  
7    3    0    0    0    0    0  
8    4    4    4    4    1    0  
9    2    2    2    2    1    0  

[10 rows x 240 columns]

In [55]:
X=X[:10]
X

0    1    2           3         4            5
0  1.0  0.0  0.0  133.150861  1.311693  1620.221779
1  1.0  0.0  0.0  126.724861  1.302745  1609.334822
2  1.0  0.0  0.0  131.173861  1.319031  1568.978435
3  1.0  0.0  0.0  129.478861  1.270878  1695.055281
4  1.0  0.0  0.0  127.262861  1.329637  1647.720235
5  1.0  0.0  0.0  131.058861  1.310403  2027.211367
6  1.0  0.0  0.0  138.442861  1.379906  1918.750472
7  1.0  0.0  0.0  129.346861  1.305646  1547.263727
8  1.0  0.0  0.0  139.542861  1.374661  1871.055934
9  1.0  0.0  0.0  132.628861  1.374434  1884.680458

In [56]:
Y.drop(Y.iloc[:, 7:], inplace = True, axis = 1) 
  

c:\users\khushi\appdata\local\programs\python\python38-32\lib\site-packages\pandas\core\frame.py:4162: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [57]:
Y

0  1  2  3  4  5  6
0  0  3  4  4  6  6  6
1  0  0  0  0  0  0  1
2  0  0  1  4  4  4  4
3  0  0  3  3  2  2  4
4  0  0  0  0  0  0  3
5  0  0  0  0  0  0  0
6  0  3  4  4  6  6  6
7  0  0  0  3  6  6  6
8  0  0  3  4  6  6  6
9  0  1  2  4  4  4  4

Our both datsets have now equal no of rows and as well as columns for ex in this (6,6)

In [58]:
Y.drop(Y.iloc[:, 6:], inplace = True, axis = 1) 
  

c:\users\khushi\appdata\local\programs\python\python38-32\lib\site-packages\pandas\core\frame.py:4162: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [59]:
Y

0  1  2  3  4  5
0  0  3  4  4  6  6
1  0  0  0  0  0  0
2  0  0  1  4  4  4
3  0  0  3  3  2  2
4  0  0  0  0  0  0
5  0  0  0  0  0  0
6  0  3  4  4  6  6
7  0  0  0  3  6  6
8  0  0  3  4  6  6
9  0  1  2  4  4  4

In [60]:
X

0    1    2           3         4            5
0  1.0  0.0  0.0  133.150861  1.311693  1620.221779
1  1.0  0.0  0.0  126.724861  1.302745  1609.334822
2  1.0  0.0  0.0  131.173861  1.319031  1568.978435
3  1.0  0.0  0.0  129.478861  1.270878  1695.055281
4  1.0  0.0  0.0  127.262861  1.329637  1647.720235
5  1.0  0.0  0.0  131.058861  1.310403  2027.211367
6  1.0  0.0  0.0  138.442861  1.379906  1918.750472
7  1.0  0.0  0.0  129.346861  1.305646  1547.263727
8  1.0  0.0  0.0  139.542861  1.374661  1871.055934
9  1.0  0.0  0.0  132.628861  1.374434  1884.680458

In [61]:
row,n=X.shape

In [62]:
n

6

## Mathematical Formulation Implementation


##  Creation of Covariance Matrix for the datasets 

Notations Used for calculation of Covariance matrices 
1. Cxy=Covariance matrices between datasets x and y
2. Cyy=Covariance matrices between datasets y and y
3. Cxx=Covariance matrices between datasets x and x

Dot function returns the dot product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication.

In [63]:
Cxy=np.dot(X,Y.T)

In [64]:
Cxy

array([[10261.80427568,     0.        ,  7018.73733232,  3642.51952756,
            0.        ,     0.        , 10261.80427568, 10128.65341428,
        10261.80427568,  7018.73733232],
       [10170.7248479 ,     0.        ,  6949.4497138 ,  3601.4497183 ,
            0.        ,     0.        , 10170.7248479 , 10043.9999865 ,
        10170.7248479 ,  6949.4497138 ],
       [ 9946.4802398 ,     0.        ,  6805.8853084 ,  3534.1165156 ,
            0.        ,     0.        ,  9946.4802398 ,  9815.3063784 ,
         9946.4802398 ,  6805.8853084 ],
       [10695.87240314,     0.        ,  7303.22008396,  3781.08890338,
            0.        ,     0.        , 10695.87240314, 10566.39354174,
        10695.87240314,  7303.22008396],
       [10403.35067526,     0.        ,  7105.25093204,  3679.88832742,
            0.        ,     0.        , 10403.35067526, 10276.08781386,
        10403.35067526,  7105.25093204],
       [12695.36606416,     0.        ,  8638.32252464,  4450.22012372,
   

In [65]:
Cxy[0]

array([10261.80427568,     0.        ,  7018.73733232,  3642.51952756,
           0.        ,     0.        , 10261.80427568, 10128.65341428,
       10261.80427568,  7018.73733232])

In [66]:
Cxy.shape

(10, 10)

In [67]:
Cyy=np.dot(Y,Y.T)
Cyy

array([[113,   0,  68,  48,   0,   0, 113,  84, 100,  75],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 68,   0,  49,  31,   0,   0,  68,  60,  67,  50],
       [ 48,   0,  31,  26,   0,   0,  48,  33,  45,  34],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [113,   0,  68,  48,   0,   0, 113,  84, 100,  75],
       [ 84,   0,  60,  33,   0,   0,  84,  81,  84,  60],
       [100,   0,  67,  45,   0,   0, 100,  84,  97,  70],
       [ 75,   0,  50,  34,   0,   0,  75,  60,  70,  53]], dtype=int64)

In [68]:
Cxx=np.dot(X,X.T)
Cxx

array([[2642850.48531615, 2624355.56156571, 2559561.67334255,
        2763608.37237644, 2686620.11389521, 3301985.32580773,
        3127237.89906667, 2524135.7472608 , 3050108.62980734,
        3071262.77428542],
       [2624355.56156571, 2606020.45720057, 2541637.33780542,
        2744322.33615119, 2667863.65176847, 3279072.96718521,
        3105458.89931845, 2506459.55922802, 3028841.80987688,
        3049892.05412081],
       [2559561.67334255, 2541637.33780542, 2478902.65027967,
        2676492.10071828, 2601933.82978217, 3197845.14216813,
        3028641.01673529, 2444593.07030639, 2953953.60033843,
        2974423.24764107],
       [2763608.37237644, 2744322.33615119, 2676492.10071828,
        2889979.79778447, 2809457.42673597, 3453207.35107734,
        3270316.29881057, 2639447.89631386, 3189613.84127655,
        3211812.94479142],
       [2686620.11389521, 2667863.65176847, 2601933.82978217,
        2809457.42673597, 2731180.57642319, 3356958.85733354,
        3179185.447704  

W below is an diagonal matrices of size(n*n)

In [69]:
row,col=(n,n)
W=[]
for i in range(col):
    c=[]
    for j in range(row):
        if i==j:
            c.append(1/n)
        else:
            c.append(0)
    W.append(c)
W


[[0.16666666666666666, 0, 0, 0, 0, 0],
 [0, 0.16666666666666666, 0, 0, 0, 0],
 [0, 0, 0.16666666666666666, 0, 0, 0],
 [0, 0, 0, 0.16666666666666666, 0, 0],
 [0, 0, 0, 0, 0.16666666666666666, 0],
 [0, 0, 0, 0, 0, 0.16666666666666666]]

In [70]:
row,col=(n,n)
I=[]
for i in range(col):
    c1=[]
    for j in range(row):
        if i==j:
            c1.append(1)
        else:
            c1.append(0)
    I.append(c1)
I


[[1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 1]]

I is identity matrix of size(n*n) made to perform subtraction of 2 matrices (I-W)

In [71]:
Diff=np.subtract(I,W)
Diff

array([[0.83333333, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.83333333, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.83333333, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.83333333, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.83333333,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.83333333]])

## Creation of Scatter Matrix Part for the datasets

Notations Used for calculation of Scatter matrices 
1. Swx=Between class scatter matrix for dataset x
2. Sbx=Within class scatter matrix for dataset x
3. Stx=Total scatter matrix for dataset x
4. Swy=Between class scatter matrix for dataset y
2. Sbx=Within class scatter matrix for dataset y
3. Stx=Total scatter matrix for dataset y

In [73]:
S=np.dot(X,Diff)
S

array([[8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.10959051e+02,
        1.09307730e+00, 1.35018482e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.05604051e+02,
        1.08562081e+00, 1.34111235e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.09311551e+02,
        1.09919251e+00, 1.30748203e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.07899051e+02,
        1.05906513e+00, 1.41254607e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.06052385e+02,
        1.10803057e+00, 1.37310020e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.09215718e+02,
        1.09200262e+00, 1.68934281e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.15369051e+02,
        1.14992133e+00, 1.59895873e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.07789051e+02,
        1.08803834e+00, 1.28938644e+03],
       [8.33333333e-01, 0.00000000e+00, 0.00000000e+00, 1.16285718e+02,
        1.14555124e+00, 

In [75]:
Sw=np.dot(S,X.T)
Sw

array([[2202375.40443012, 2186962.96797143, 2132968.06111879,
        2303006.97698037, 2238850.09491268, 2751654.4381731 ,
        2606031.58255556, 2103446.45605067, 2541757.19150612,
        2559385.64523785],
       [2186962.96797143, 2171683.71433381, 2118031.11483785,
        2286935.28012599, 2223219.70980706, 2732560.80598767,
        2587882.41609871, 2088716.29935669, 2524034.84156406,
        2541576.71176734],
       [2132968.06111879, 2118031.11483785, 2065752.2085664 ,
        2230410.0839319 , 2168278.19148515, 2664870.95180677,
        2523867.51394608, 2037160.89192199, 2461628.00028203,
        2478686.03970089],
       [2303006.97698037, 2286935.28012599, 2230410.0839319 ,
        2408316.49815373, 2341214.52227998, 2877672.79256445,
        2725263.58234214, 2199539.91359489, 2658011.53439712,
        2676510.78732618],
       [2238850.09491268, 2223219.70980706, 2168278.19148515,
        2341214.52227998, 2275983.81368599, 2797465.71444462,
        2649321.20642   

In [76]:
Sw.shape

(10, 10)

In [79]:
temp=Sw
temp
temp=temp/6
temp

array([[367062.56740502, 364493.82799524, 355494.67685313,
        383834.49616339, 373141.68248545, 458609.07302885,
        434338.59709259, 350574.40934178, 423626.19858435,
        426564.27420631],
       [364493.82799524, 361947.2857223 , 353005.18580631,
        381155.880021  , 370536.61830118, 455426.80099795,
        431313.73601645, 348119.38322611, 420672.47359401,
        423596.11862789],
       [355494.67685313, 353005.18580631, 344292.03476107,
        371735.01398865, 361379.69858086, 444145.15863446,
        420644.58565768, 339526.81532033, 410271.33338034,
        413114.33995015],
       [383834.49616339, 381155.880021  , 371735.01398865,
        401386.08302562, 390202.42038   , 479612.13209408,
        454210.59705702, 366589.98559915, 443001.92239952,
        446085.13122103],
       [373141.68248545, 370536.61830118, 361379.69858086,
        390202.42038   , 379330.63561433, 466244.28574077,
        441553.53440333, 356377.99165406, 430658.0799181 ,
        433

In [80]:
Sw=temp
Sw

array([[367062.56740502, 364493.82799524, 355494.67685313,
        383834.49616339, 373141.68248545, 458609.07302885,
        434338.59709259, 350574.40934178, 423626.19858435,
        426564.27420631],
       [364493.82799524, 361947.2857223 , 353005.18580631,
        381155.880021  , 370536.61830118, 455426.80099795,
        431313.73601645, 348119.38322611, 420672.47359401,
        423596.11862789],
       [355494.67685313, 353005.18580631, 344292.03476107,
        371735.01398865, 361379.69858086, 444145.15863446,
        420644.58565768, 339526.81532033, 410271.33338034,
        413114.33995015],
       [383834.49616339, 381155.880021  , 371735.01398865,
        401386.08302562, 390202.42038   , 479612.13209408,
        454210.59705702, 366589.98559915, 443001.92239952,
        446085.13122103],
       [373141.68248545, 370536.61830118, 361379.69858086,
        390202.42038   , 379330.63561433, 466244.28574077,
        441553.53440333, 356377.99165406, 430658.0799181 ,
        433

In [81]:
t=np.dot(X,W)
Sb=np.dot(t,X.T)
Sb

array([[440475.08088602, 437392.59359429, 426593.61222376,
        460601.39539607, 447770.01898254, 550330.88763462,
        521206.31651111, 420689.29121013, 508351.43830122,
        511877.12904757],
       [437392.59359429, 434336.74286676, 423606.22296757,
        457387.0560252 , 444643.94196141, 546512.16119753,
        517576.48321974, 417743.25987134, 504806.96831281,
        508315.34235347],
       [426593.61222376, 423606.22296757, 413150.44171328,
        446082.01678638, 433655.63829703, 532974.19036135,
        504773.50278922, 407432.1783844 , 492325.60005641,
        495737.20794018],
       [460601.39539607, 457387.0560252 , 446082.01678638,
        481663.29963075, 468242.904456  , 575534.55851289,
        545052.71646843, 439907.98271898, 531602.30687942,
        535302.15746524],
       [447770.01898253, 444643.94196141, 433655.63829703,
        468242.904456  , 455196.7627372 , 559493.14288892,
        529864.241284  , 427653.58998487, 516789.69590172,
        520

In [83]:
Sb=Sb/n
Sb

array([[12235.4189135 , 12149.79426651, 11849.82256177, 12794.48320545,
        12438.05608285, 15286.96910096, 14477.95323642, 11685.81364473,
        14120.87328615, 14218.80914021],
       [12149.79426651, 12064.90952408, 11766.83952688, 12705.1960007 ,
        12351.22061004, 15180.8933666 , 14377.12453388, 11603.97944087,
        14022.41578647, 14119.87062093],
       [11849.82256177, 11766.83952688, 11476.4011587 , 12391.16713295,
        12045.9899527 , 14804.83862115, 14021.48618859, 11317.56051068,
        13675.71111268, 13770.47799834],
       [12794.48320545, 12705.1960007 , 12391.16713295, 13379.53610085,
        13006.747346  , 15987.0710698 , 15140.35323523, 12219.66618664,
        14766.73074665, 14869.50437403],
       [12438.05608285, 12351.22061004, 12045.9899527 , 13006.747346  ,
        12644.35452048, 15541.47619136, 14718.45114678, 11879.26638847,
        14355.2693306 , 14455.12816148],
       [15286.96910096, 15180.8933666 , 14804.83862115, 15987.0710698 ,
   

In [84]:
Swx=Sw
Swx
Sbx=Sb


array([[12235.4189135 , 12149.79426651, 11849.82256177, 12794.48320545,
        12438.05608285, 15286.96910096, 14477.95323642, 11685.81364473,
        14120.87328615, 14218.80914021],
       [12149.79426651, 12064.90952408, 11766.83952688, 12705.1960007 ,
        12351.22061004, 15180.8933666 , 14377.12453388, 11603.97944087,
        14022.41578647, 14119.87062093],
       [11849.82256177, 11766.83952688, 11476.4011587 , 12391.16713295,
        12045.9899527 , 14804.83862115, 14021.48618859, 11317.56051068,
        13675.71111268, 13770.47799834],
       [12794.48320545, 12705.1960007 , 12391.16713295, 13379.53610085,
        13006.747346  , 15987.0710698 , 15140.35323523, 12219.66618664,
        14766.73074665, 14869.50437403],
       [12438.05608285, 12351.22061004, 12045.9899527 , 13006.747346  ,
        12644.35452048, 15541.47619136, 14718.45114678, 11879.26638847,
        14355.2693306 , 14455.12816148],
       [15286.96910096, 15180.8933666 , 14804.83862115, 15987.0710698 ,
   

In [86]:
Swx

array([[367062.56740502, 364493.82799524, 355494.67685313,
        383834.49616339, 373141.68248545, 458609.07302885,
        434338.59709259, 350574.40934178, 423626.19858435,
        426564.27420631],
       [364493.82799524, 361947.2857223 , 353005.18580631,
        381155.880021  , 370536.61830118, 455426.80099795,
        431313.73601645, 348119.38322611, 420672.47359401,
        423596.11862789],
       [355494.67685313, 353005.18580631, 344292.03476107,
        371735.01398865, 361379.69858086, 444145.15863446,
        420644.58565768, 339526.81532033, 410271.33338034,
        413114.33995015],
       [383834.49616339, 381155.880021  , 371735.01398865,
        401386.08302562, 390202.42038   , 479612.13209408,
        454210.59705702, 366589.98559915, 443001.92239952,
        446085.13122103],
       [373141.68248545, 370536.61830118, 361379.69858086,
        390202.42038   , 379330.63561433, 466244.28574077,
        441553.53440333, 356377.99165406, 430658.0799181 ,
        433

In [87]:
Stx=np.dot(X,X.T)
Stx

array([[2642850.48531615, 2624355.56156571, 2559561.67334255,
        2763608.37237644, 2686620.11389521, 3301985.32580773,
        3127237.89906667, 2524135.7472608 , 3050108.62980734,
        3071262.77428542],
       [2624355.56156571, 2606020.45720057, 2541637.33780542,
        2744322.33615119, 2667863.65176847, 3279072.96718521,
        3105458.89931845, 2506459.55922802, 3028841.80987688,
        3049892.05412081],
       [2559561.67334255, 2541637.33780542, 2478902.65027967,
        2676492.10071828, 2601933.82978217, 3197845.14216813,
        3028641.01673529, 2444593.07030639, 2953953.60033843,
        2974423.24764107],
       [2763608.37237644, 2744322.33615119, 2676492.10071828,
        2889979.79778447, 2809457.42673597, 3453207.35107734,
        3270316.29881057, 2639447.89631386, 3189613.84127655,
        3211812.94479142],
       [2686620.11389521, 2667863.65176847, 2601933.82978217,
        2809457.42673597, 2731180.57642319, 3356958.85733354,
        3179185.447704  

In [89]:
Stx=Stx/n
Stx

array([[ 73412.513481  ,  72898.76559905,  71098.93537063,
         76766.89923268,  74628.33649709,  91721.81460577,
         86867.71941852,  70114.88186836,  84725.23971687,
         85312.85484126],
       [ 72898.76559905,  72389.45714446,  70601.03716126,
         76231.1760042 ,  74107.32366024,  91085.36019959,
         86262.74720329,  69623.87664522,  84134.4947188 ,
         84719.22372558],
       [ 71098.93537063,  70601.03716126,  68858.40695221,
         74347.00279773,  72275.93971617,  88829.03172689,
         84128.91713154,  67905.36306407,  82054.26667607,
         82622.86799003],
       [ 76766.89923268,  76231.1760042 ,  74347.00279773,
         80277.21660512,  78040.484076  ,  95922.42641882,
         90842.1194114 ,  73317.99711983,  88600.3844799 ,
         89217.02624421],
       [ 74628.33649709,  74107.32366024,  72275.93971617,
         78040.484076  ,  75866.12712287,  93248.85714815,
         88310.70688067,  71275.59833081,  86131.61598362,
         86

In [90]:
S1=np.dot(Y,Diff)
S1

array([[0.        , 2.5       , 3.33333333, 3.33333333, 5.        ,
        5.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.83333333, 3.33333333, 3.33333333,
        3.33333333],
       [0.        , 0.        , 2.5       , 2.5       , 1.66666667,
        1.66666667],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 2.5       , 3.33333333, 3.33333333, 5.        ,
        5.        ],
       [0.        , 0.        , 0.        , 2.5       , 5.        ,
        5.        ],
       [0.        , 0.        , 2.5       , 3.33333333, 5.        ,
        5.        ],
       [0.        , 0.83333333, 1.66666667, 3.33333333, 3.33333333,
        3.33333333]])

In [92]:
Swy=np.dot(S1,Y.T)
Swy
Swy=Swy/n

In [94]:
S3=np.dot(Y,W)
Sby=np.dot(S3,Y.T)
Sby
Sby=Sby/n

In [95]:
Sty=np.dot(Y,Y.T)
Sty=Sty/n
Sty

array([[18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        , 16.66666667, 12.5       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [11.33333333,  0.        ,  8.16666667,  5.16666667,  0.        ,
         0.        , 11.33333333, 10.        , 11.16666667,  8.33333333],
       [ 8.        ,  0.        ,  5.16666667,  4.33333333,  0.        ,
         0.        ,  8.        ,  5.5       ,  7.5       ,  5.66666667],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [18.83333333,  0.        , 11.33333333,  8.        ,  0.        ,
         0.        , 18.83333333, 14.        

### Use of Lagrangian multiplier technique for calculation of final projection vectors wx,wy  