In [1]:
from MCCA import MCCA
import pandas as pd
import numpy as np 
import os
os.chdir(r'C:/Users/Mansi/Downloads/')
os.getcwd()
X1=pd.read_csv('mfeat-fac', delim_whitespace=True,header=None)
X2=pd.read_csv('mfeat-zer', delim_whitespace=True,header=None)
X3=pd.read_csv('mfeat-kar', delim_whitespace=True,header=None)

In [2]:
print(X1.shape,X2.shape,X3.shape)

(2000, 216) (2000, 47) (2000, 64)


In [3]:
X1.head()

0    1    2    3    4    5    6    7    8    9    ...  206  207  208  209  \
0   98  236  531  673  607  647    2    9    3    6  ...  474  536  628  632   
1  121  193  607  611  585  665    7    9    2    4  ...  520  458  570  634   
2  115  141  590  605  557  627   12    6    3    3  ...  535  498  572  656   
3   90  122  627  692  607  642    0    6    4    5  ...  576  549  628  621   
4  157  167  681  666  587  666    8    6    1    4  ...  594  525  568  653   

   210  211  212  213  214  215  
0   18   36    8   15   12   13  
1   15   32   11   13   15   11  
2   20   35   16   14   13    6  
3   16   35    7   12   15    9  
4   16   35   10   15   13   13  

[5 rows x 216 columns]

In [4]:
X2.head()

0         1          2          3           4           5   \
0  0.011033  0.831466  15.351804  75.806559  171.554214  490.156556   
1  0.038271  1.166746  10.526913  42.369276   85.187116  420.360566   
2  0.042698  1.225007   8.273804  31.744786   54.448177  404.103204   
3  0.032418  1.638247  19.205283  51.196682   57.181760  429.052011   
4  0.015866  0.611561   8.627839  37.325052   48.509025  459.909634   

           6         7         8          9   ...        37         38  \
0  206.416027  0.122135  2.601646  11.472709  ...  1.713529  33.810340   
1  253.569574  0.033657  0.390566  11.700830  ...  2.590208  35.400531   
2  389.980746  0.041733  0.937399  11.629045  ...  1.476285  19.477230   
3  256.174645  0.073624  1.973268  13.057108  ...  1.349613  14.179518   
4  238.572767  0.046477  1.117292  10.012169  ...  0.667971   8.705403   

          39        40          41          42        43         44  \
0   9.858915  1.399891  148.138058  326.239452  9.711070  20.007248   
1  70.681899  6.674412  155.135985  377.832675  8.140633  44.536711   
2  30.093590  7.858211  150.126419  419.565747  4.530921  26.292170   
3  30.564085  7.097728  173.840759  441.350376  3.706023  13.432311   
4  30.242473  9.015714  167.021185  332.479997  1.806273  23.689300   

          45          46  
0  47.032578  539.208457  
1  46.338954  518.496567  
2  44.574822  549.912691  
3  51.739930  574.887814  
4  50.407770  492.227513  

[5 rows x 47 columns]

In [5]:
X3.head()

0          1          2         3         4         5         6   \
0 -10.297008 -11.666789  11.560669 -2.081316  4.044656  4.086815 -2.558072   
1  -5.036009 -12.885333   0.161155  0.592460  3.123534  4.220469 -6.411771   
2  -9.639157  -6.655898   0.388687 -1.717650  0.300346  3.400769 -7.240785   
3  -6.650375  -7.043851   4.104350 -2.342780  3.494658  3.924822 -9.874812   
4 -10.664524 -10.974133   0.194391  0.453885  2.193088 -3.304663 -8.376592   

         7         8         9   ...        54        55        56        57  \
0 -8.476935  2.138135  3.503082  ...  1.078083  0.921927  0.496387 -0.643667   
1 -6.335328 -0.244622  1.346073  ...  0.942353  2.938791  1.429883 -2.336344   
2 -1.659405 -0.874005  4.153403  ... -0.413174 -0.023028 -0.025265  1.259838   
3 -6.556576 -1.364269  1.153308  ... -0.961236 -1.043815 -0.204508 -1.981150   
4 -4.241146  2.964818 -0.949622  ...  0.152957  1.448160 -1.254907 -3.481295   

         58        59        60        61        62        63  
0  0.284104  0.286555  0.348625  1.814691 -1.351353 -0.473910  
1  1.281628 -0.098321  0.582357  0.485792  0.642451  0.613107  
2 -0.441360 -0.960094  1.995843  1.097748  0.827182 -1.767840  
3  0.982438 -0.144233 -1.449328 -0.913552 -0.771735  0.304992  
4 -0.563889  1.529335  0.510399  0.298318 -0.943213  1.149847  

[5 rows x 64 columns]

In [6]:
X_list =[X1,X2,X3]
mcca = MCCA(n_components=3,reg_param=0.001)
mcca.fit([X1,X2,X3])
X_reduced = mcca.transform([X1,X2,X3])
for i in range(len(X_reduced)):
    print("X_reduced_{0}->{1}\n".format(i+1,X_reduced[i]))
  

X_reduced_1->[[ -6.40383538  -8.38274307  -8.82365405]
 [ -6.13753381  -7.21874964  -7.40564907]
 [ -9.357691   -10.01336443 -10.04164193]
 ...
 [ -1.68682806   0.17224245   1.18643763]
 [ -3.88547497  -2.17918367  -1.0756717 ]
 [  6.39664501   7.96717436   8.56899963]]

X_reduced_2->[[-4.8394304  -5.50990786 -5.71162583]
 [-4.36378386 -4.62362686 -4.70344613]
 [-5.40537159 -5.70009601 -5.8528085 ]
 ...
 [-3.44751041 -3.19407567 -3.07131435]
 [-4.80371785 -4.85059495 -4.68830153]
 [-1.69368068 -1.13819571 -0.97487043]]

X_reduced_3->[[-0.51888371 -1.157758   -1.34055804]
 [-0.93567599 -1.78505533 -2.12606296]
 [-0.84587507 -0.6798663  -0.58610479]
 ...
 [-1.81837991 -0.81884403 -0.21213098]
 [-1.46558645 -1.14811724 -0.91876814]
 [ 0.73999371  1.41143721  1.75330205]]



C:\Users\MANSI\Desktop\MCCA.py:90: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  weights[i] = np.hstack(x.reshape(dimen[i],1) for x in weights[i])


In [7]:
X_list =[X1,X2,X3]
m = MCCA(n_components=6,reg_param=0.001)
m.fit([X1,X2,X3])
X_reduced = m.transform([X1,X2,X3])
for i in range(len(X_reduced)):
    print("X_reduced_{0}->{1}\n".format(i+1,X_reduced[i]))

X_reduced_1->[[-6.70347707 -8.33908777 -8.72807047 -8.85256256 -8.901298   -8.92452828]
 [-5.93397571 -6.91381318 -7.15672568 -7.20789273 -7.21043148 -7.20382436]
 [-9.222859   -9.70941959 -9.78310506 -9.76592441 -9.73694239 -9.71418323]
 ...
 [-0.16143189  1.16775068  1.79098948  2.11622286  2.2981092   2.40318695]
 [-2.13524411 -0.9535096  -0.29738658  0.08303097  0.31148704  0.45031822]
 [ 7.53085045  8.55031189  8.87444099  9.01156359  9.0734788   9.10159501]]

X_reduced_2->[[-4.8528837  -5.54758897 -5.72907345 -5.78887839 -5.81430745 -5.82756485]
 [-4.38297919 -4.63962854 -4.70936542 -4.73533219 -4.74617751 -4.75105202]
 [-5.58903298 -5.82652762 -5.92955822 -5.98775012 -6.02234804 -6.04354685]
 ...
 [-3.2538565  -3.09870931 -3.01693483 -2.97431383 -2.94806501 -2.93077896]
 [-4.48775768 -4.61161651 -4.52935534 -4.44945818 -4.38828934 -4.34437784]
 [-1.4859907  -1.03579646 -0.92211534 -0.88208142 -0.86061673 -0.84648688]]

X_reduced_3->[[-0.55864656 -1.16563929 -1.32878139 -1.387644

C:\Users\MANSI\Desktop\MCCA.py:90: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  weights[i] = np.hstack(x.reshape(dimen[i],1) for x in weights[i])
