In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
import rgcca

In [3]:
x1 = np.random.randn(4,5)
x2 = np.random.randn(4,6)
x3 = np.random.randn(4,5)
x4 = np.random.randn(4,6)
x5 = np.random.randn(4,7)

In [4]:
rgc = rgcca.RGCCA()

In [5]:
rgc.fit([x1,x2,x3,x4,x5])

In [7]:
res = rgc.transform([x1,x2,x3,x4,x5])
print(res)

[array([[-0.16949665,  0.05793227],
       [-0.0211854 , -0.16001056],
       [ 0.10798999, -0.03515629],
       [ 0.08269206,  0.13723458]]), array([[-0.17090446,  0.0609658 ],
       [-0.02197387, -0.16084664],
       [ 0.114171  , -0.03672295],
       [ 0.07870733,  0.1366038 ]]), array([[-0.17219026,  0.05880788],
       [-0.02196213, -0.15672825],
       [ 0.11426655, -0.03811533],
       [ 0.07988584,  0.1360357 ]]), array([[-0.17219929,  0.06023548],
       [-0.02200528, -0.16072357],
       [ 0.11385121, -0.0369466 ],
       [ 0.08035336,  0.13743469]]), array([[-0.17245942,  0.0605209 ],
       [-0.02066908, -0.15806151],
       [ 0.11352794, -0.03623691],
       [ 0.07960056,  0.13377752]])]


In [9]:
abc = rgcca.RGCCA()
res1 = abc.fit_transform([x1,x2,x3,x4,x5])

[array([[-0.16949665,  0.05793227],
       [-0.0211854 , -0.16001056],
       [ 0.10798999, -0.03515629],
       [ 0.08269206,  0.13723458]]), array([[-0.17090446,  0.0609658 ],
       [-0.02197387, -0.16084664],
       [ 0.114171  , -0.03672295],
       [ 0.07870733,  0.1366038 ]]), array([[-0.17219026,  0.05880788],
       [-0.02196213, -0.15672825],
       [ 0.11426655, -0.03811533],
       [ 0.07988584,  0.1360357 ]]), array([[-0.17219929,  0.06023548],
       [-0.02200528, -0.16072357],
       [ 0.11385121, -0.0369466 ],
       [ 0.08035336,  0.13743469]]), array([[-0.17245942,  0.0605209 ],
       [-0.02066908, -0.15806151],
       [ 0.11352794, -0.03623691],
       [ 0.07960056,  0.13377752]])]


In [10]:
rgc.weights

[array([[ 0.07076432, -0.05528831],
        [-0.07778884,  0.04116878],
        [-0.00763935, -0.05428245],
        [-0.05175223, -0.0253489 ],
        [ 0.02329436, -0.00464579]]),
 array([[-0.0353552 ,  0.0307235 ],
        [ 0.01490408, -0.01447572],
        [ 0.0460204 , -0.01135475],
        [ 0.0383193 ,  0.03107638],
        [ 0.02838632, -0.01749865],
        [ 0.04974561,  0.05493907]]),
 array([[-0.00916377, -0.0214017 ],
        [ 0.05020281, -0.0219377 ],
        [-0.04579865, -0.0108178 ],
        [ 0.01722792, -0.00331134],
        [ 0.01188978,  0.11156725]]),
 array([[ 0.01338884, -0.04091204],
        [-0.02425717, -0.03513895],
        [-0.04830855, -0.00490196],
        [ 0.03599462, -0.02984957],
        [-0.02779467, -0.01062314],
        [-0.00703663, -0.03264378]]),
 array([[-0.01465044,  0.02532783],
        [-0.05515995, -0.0717137 ],
        [-0.00725292,  0.06431659],
        [-0.02070039,  0.03913111],
        [-0.02456448, -0.05027572],
        [-0.04061569